.github/workflows/gradle.yml
create github action deploy gradle.yml
=> Create deploy - gradle.yml

.github/workflows/gradle.yml
gradlew 파일을 찾지 못해 경로를 변경하여 다시 업데이트
=> Update CD - gradle

frontend/.eslintrc.json, frontend/.gitignore, frontend/.prettierrc.json
What kind of change does this PR introduce?
=> 프론트엔드 환경설정 파일 복구

.github/workflows/ci.yml
=> [feature] Create ci.yml

backend/src/main/java/kr/co/yigil/global/config/SecurityConfig.java, backend/src/main/java/kr/co/yigil/login/application/strategy/GoogleLoginStrategy.java, backend/src/main/java/kr/co/yigil/login/application/strategy/KakaoLoginStrategy.java, backend/src/main/java/kr/co/yigil/login/application/strategy/LoginStrategy.java, backend/src/main/java/kr/co/yigil/login/dto/request/GoogleLoginRequest.java, backend/src/main/java/kr/co/yigil/login/dto/request/KakaoLoginRequest.java, backend/src/main/java/kr/co/yigil/login/dto/request/LoginRequest.java, backend/src/main/java/kr/co/yigil/login/dto/response/GoogleLoginResponse.java, backend/src/main/java/kr/co/yigil/login/dto/response/KakaoLoginResponse.java, backend/src/main/java/kr/co/yigil/login/dto/response/KakaoTokenInfoResponse.java, backend/src/main/java/kr/co/yigil/login/dto/response/LoginResponse.java, backend/src/main/java/kr/co/yigil/login/presentation/LoginController.java, backend/src/main/java/kr/co/yigil/member/domain/Member.java, backend/src/main/java/kr/co/yigil/member/domain/repository/MemberRepository.java, backend/src/test/java/kr/co/yigil/login/application/strategy/KakaoLoginStrategyTest.java, backend/src/test/java/kr/co/yigil/login/presentation/LoginControllerTest.java
카카오 로그인 구현 및 테스트 코드 작성을 완료했습니다.
#49 
@Uknow928 님이 고생해주신 덕에 Redis도 잘 연결해서 기능을 완료하고 테스트도 통과함을 확인해서 PR날립니다.
리뷰 부탁드립니다.
참고로 RestTemplate 관련 테스트 코드 작성에 어려움이 있어서, 부득이하게 Strategy 테스트를 단위 테스트가 아닌 통합 테스트로 작성한 점 양해를 부탁 드립니다
=> 카카오 로그인 API 구현 및 테스트

backend/.gitignore
What kind of change does this PR introduce?
#60 ci 파일 관련해서 민감한 정보를 담은 파일을 담지 않아 생기는 오류를 해결하기 위해, 해당 파일을 필요로 하는 Jasypt test 클래스를 서버에 올리지 않도록 변경해서 테스트를 진행해보기로 했습니다.
=> fix jasyptApplicationTest.java 파일이 서버에 올라가지 않도록 변경

frontend/src/app/api/auth/[...nextauth]/route.ts, frontend/src/types/type.d.ts
- `NodeJS`의 `ProcessEnv`에 대한 타입을 선언합니다.
- `types/type.d.ts` 파일을 생성하여, `ProcessEnv`에 대해 타입을 선언합니다.
- `route.ts`에서 환경변수에 접근할 때 falsy한 값을 걸러내는 로직을 제거합니다.
=> `ProcessEnv` 타입 선언

.github/workflows/frontend-ci.yml
- 프론트엔드 코드베이스에 테스트 프레임워크를 도입하였으므로, 수정 발생 시 테스트 검사를 진행하도록 CI workflow를 작성하였습니다.
- 프론트엔드 코드베이스에 대한 CI의 동작을 정의하는 `frontend-ci.yml` 파일을 작성하였습니다.
- 현재는 테스트만을 위해 워크플로우를 작성하였으나, 이후 CI 환경이 필요한 작업이 있다면 추가할 수 있습니다.
=> 프론트엔드 CI workflow 작성 및 테스트 CI에 적용

frontend/public/mockServiceWorker.js, frontend/src/app/_components/ui/button/GoogleLoginButton.tsx
- SVGR 적용 이전에 `.svg` 파일을 `next/image` 컴포넌트로 렌더링하던 코드를 업데이트했습니다.
- `.svg` 파일을 컴포넌트로 import(첫 글자 대문자)
- 기존 코드 교체 후 알맞은 className 지정
=> fix: SVGR 적용 후 보이지 않던 구글 로그인 버튼 로고 보이도록 수정

frontend/README.md
- FE 크루 중간점검에 따른 사항 작성
- `frontend` 디렉토리 내 `README.md`에 중간점검에 필요한 내용 작성
ASAP~
=> docs: 프론트엔드 중간 점검 관련 글 작성

backend/yigil-api/src/main/java/kr/co/yigil/comment/domain/repository/CommentRepository.java, backend/yigil-api/src/test/java/kr/co/yigil/comment/application/CommentRedisIntegrityServiceTest.java
기존에 사용되던  querymethod를 대체하여 별도의 메서드를 생성하였는데 테스트 코드는 수정하지 않아서 예전의 쿼리 메소드를 사용해서 에러가 발생하였습니다.
<br>
<br>
=> fix comment test 수정 및  commentRepository수정

frontend/.dockerignore, frontend/Dockerfile, frontend/app.json, frontend/next.config.js
프론트엔드/백엔드 동시 배포를 위한 Dockerize 작업입니다.
1. Dockerfile 및 `.dockerignore` 파일을 만들고 내용을 작성했습니다.
2. 컨테이너의 환경을 명시하는 `app.json` 파일을 만들었습니다.
3. Next.js 프로젝트를 프로덕션에 배포할 때, 필요한 파일들만을 복사하여 하나의 디렉토리에 몰아넣는 설정인 `output: "standalone"`을 적용하였습니다.
=> 프론트엔드 배포를 위한 Docker 파일 생성 및 설정

backend/support/Dockerfile, backend/yigil-admin/Dockerfile, backend/yigil-admin/build.gradle, proxy/nginx.conf
- 기존에 vercel로 프론트엔드를 올렸지만 이제 백엔드와 같이 올릴 필요가 있음
<br>
- nginx 기능을 추가 후 docker-compose 수정을 진행함.
<br>
- 이전 회의에서 여러 변경 사항이 생겨 테스트가 통과하지 않습니다.
- 추후 도메인 연결 및 admin까지 추가할 계획입니다.
=> feat: Upload backend and frontend to ec2 through nginx

frontend/src/app/_components/mypage/MyPageInfo.tsx, frontend/src/app/_components/mypage/MyPlace.tsx
마이페이지의 마이페이지에서 디자인 변경에 따라 스타일을 조금 수정했습니다.
<br>
장소와 일정 탭 부분 margin-left 추가
<br>
=> 마이페이지 / 마이페이지 디자인 변경에 따른 스타일 수정

frontend/src/app/_components/search/SearchBar.tsx, frontend/src/app/_components/search/SearchHistory.tsx
발견된 디자인적 오류를 수정합니다.
- Chrome에서 SearchBar가 남은 영역을 차지하도록 변경하였습니다.
- 디자인과 일치하지 않는 부분을 디자인에 맞게 수정하였습니다.
=> Search 컴포넌트 스타일 수정

frontend/src/app/_components/ui/popover/PopOver.tsx
pop over 내부의 간격 사이즈가 변경되어 pop over에서의 gap 사이즈를 변경했습니다.
=> style: pop over 디자인 변경에 따른 gap 사이즈 변경

backend/support/domain/src/main/java/kr/co/yigil/place/Place.java, backend/support/domain/src/main/java/kr/co/yigil/travel/Course.java, backend/support/domain/src/main/java/kr/co/yigil/travel/Spot.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/dto/request/CourseUpdateRequest.java, backend/yigil-api/src/test/java/kr/co/yigil/comment/application/CommentRedisIntegrityServiceTest.java, backend/yigil-api/src/test/java/kr/co/yigil/comment/application/CommentServiceTest.java, backend/yigil-api/src/test/java/kr/co/yigil/favor/application/FavorRedisIntegrityServiceTest.java, backend/yigil-api/src/test/java/kr/co/yigil/favor/application/FavorServiceTest.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/application/CourseServiceTest.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/application/SpotServiceTest.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/application/TravelServiceTest.java
- 작업한 내용에 맞춰 테스트 코드를 업데이트 하였습니다. 
<br>
<br>
=> 도메인 수정에 맞춰 테스트 코드 수정

frontend/package-lock.json, frontend/package.json, frontend/src/app/_components/add/common/AddSpotMap.tsx, frontend/src/app/_components/naver-map/MapComponent.tsx, frontend/src/app/_components/naver-map/hooks/getArea.ts, frontend/src/app/_components/naver-map/hooks/getCoords.ts, frontend/src/app/layout.tsx, frontend/src/context/NaverContext.tsx, frontend/src/types/type.d.ts, frontend/tsconfig.json
#253 에 따라 지도 컴포넌트를 추가하고 마커를 표시할 수 있게 컴포넌트를 생성했습니다.
<br>
<br>
`getArea` 함수로 검색 후에 여러 개의 데이터가 나온다면 선택한 데이터를 `getCoords` 함수에 인수로 넘겨야 하고, `getArea`에서 얻은 title이 `<b>title</b>`로 되어 있어 파싱을 진행해야 합니다.
=> 장소 추가 지도 추가

frontend/src/app/(with-header)/(mypage)/mypage/layout.tsx, frontend/src/app/_components/mypage/hooks/myPageActions.ts, frontend/src/app/_components/mypage/spot/MyPageSpotList.tsx
기존에 마이페이지에서 사용되던 `httpRequest`를 함수 이름이 수정됨에 따라 같이 수정합니다.
마이 페이지 파일 외 다른 파일에 존재하는 `httpRequest`는 정욱님이 작업하시는 파일인 관계로 작업하시며 수정해주실 예정입니다.
=> http request 함수 이름 수정에 따른 코드 수정

frontend/src/middleware.ts
로그인되어있지 않은 상황에서 접근하면 안 되는 페이지들에 접근하려 할 때, 로그인 페이지로 리다이렉트 처리되도록 미들웨어를 설정했습니다.
- 미들웨어 설정을 담는 `middleware.ts` 파일을 작성하였습니다.
=> Middleware를 통해 접근 제한 설정

frontend/package-lock.json, frontend/package.json
#198 에 의거하여, 프로덕션 빌드에서 권장되는 이미지 로더를 프로젝트에 추가합니다.
- [`sharp`](https://www.npmjs.com/package/sharp) 추가
https://nextjs.org/docs/messages/sharp-missing-in-production
=> Next.js의 프로덕션 빌드에서 사용이 권장되는 이미지 로더 추가

backend/support/domain/src/main/java/kr/co/yigil/bookmark/domain/Bookmark.java, backend/yigil-api/src/docs/asciidoc/bookmark-api.adoc, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/application/BookmarkFacade.java, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/domain/BookmarkService.java, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/domain/BookmarkServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/interfaces/controller/BookmarkApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/interfaces/dto/BookmarkInfoDto.java, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/interfaces/dto/mapper/BookmarkMapper.java, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/interfaces/dto/response/AddBookmarkResponse.java, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/interfaces/dto/response/BookmarksResponse.java, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/interfaces/dto/response/DeleteBookmarkResponse.java, backend/yigil-api/src/main/java/kr/co/yigil/global/config/JpaConfig.java, backend/yigil-api/src/main/resources/static/docs/bookmark-api.html, backend/yigil-api/src/main/resources/static/docs/index.html, backend/yigil-api/src/main/resources/static/docs/notification-api.html, backend/yigil-api/src/test/java/kr/co/yigil/bookmark/interfaces/controller/BookmarkApiControllerTest.java
- bookmark 리스트 조회 기능 추가
<br>
- bookmark 리스트 조회 기능 추가
<br>
- 경택님이 말씀하신  여러 정렬 기준은 아직 추가되지 않은 상태입니다! 
- 현재 rate은 5.0으로 고정되어 있습니다
=> bookmark 리스트 조회 기능 추가

frontend/src/app/_components/add/common/AddConfirmContent.tsx
기존 작업해두었던 url과 현재 url의 차이가 생겨 link 태그의 href 값을 변경했습니다. 
<br>
<br>
=> fix: 장소 추가 후 마이페이지 이동 클릭 시 이동되는 url 변경

backend/support/domain/src/main/java/kr/co/yigil/member/Member.java, backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberInfo.java
Reverts Kernel360/f1-Yigil#303
=> Revert "hotfix: member cdn profile image address 수정"

backend/support/domain/src/main/java/kr/co/yigil/member/Member.java, backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberInfo.java
=> hotfix member cdn 수정

backend/support/domain/src/main/java/kr/co/yigil/member/Member.java, backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberInfo.java
=> merge refactoring to Develop

frontend/src/app/_components/mypage/Pagination.tsx
페이지네이션 버튼 비활성화 중에도 버튼이 보이는 현상을 수정했습니다
<br>
<br>
=> style: 버튼 비활성화시에도 보이는 문제 해결

frontend/src/app/_components/mypage/Pagination.tsx
<br>
tab index 추가 및 `Enter` 시 동작하게 수정했습니다.
<br>
=> fix: button 자체를 조건부 렌더링 하니 페이지 번호들의 레이아웃 쉬프트 현상으로 코드 수정

frontend/src/app/_components/mypage/spot/MyPageSpotItem.tsx
`IconWithCounts` 컴포넌트의 스타일을 수정했습니다.
`created_date` 가 기본 `date` 타입으로 되어 있어 디자인처럼 `localeDateString` 처리 했습니다.
<br>
<br>
=> style: 마이 페이지 스팟의 스타일 변경

backend/yigil-admin/src/main/java/kr/co/yigil/global/config/SecurityConfig.java, backend/yigil-api/src/test/java/kr/co/yigil/bookmark/interfaces/controller/BookmarkApiControllerTest.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/CourseApiControllerTest.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/SpotApiControllerTest.java
명세서 정렬 정보 구체화
<br>
명세서 정렬 정보 구체화를 위해 test adoc 부분 수정
<br>
=> docs : 정렬 파라미터 정보 adoc에 추가

frontend/src/app/_components/add/common/action.ts
백엔드에서 CDN URL이 포함된 전체 URL을 보내주기로 변경되었는데, 코드상에 반영되지 않았던 부분을 수정합니다.
백엔드에서 보내주는 URL 그대로 넘겨주도록 합니다.
=> 장소 추가 시 지도 이미지가 올바르게 뜨지 않던 문제 해결

backend/place-region-batch/src/main/java/kr/co/yigil/BatchApplication.java, backend/place-region-batch/src/main/java/kr/co/yigil/batch/job/PopularPlaceJobConfig.java, backend/place-region-batch/src/main/java/kr/co/yigil/batch/job/UpdateRegionJobConfig.java, backend/support/domain/src/main/java/kr/co/yigil/place/domain/PopularPlace.java, backend/support/domain/src/main/java/kr/co/yigil/place/infrastructure/PopularPlaceRepository.java, backend/support/domain/src/main/java/kr/co/yigil/travel/infrastructure/SpotRepository.java
- 인기 장소 선정을 위한 스프링 배치 애플리케이션 추가
<br>
- Popular Place라는 신규 테이블에 1주일간 가장 많은 Spot이 생성된 Place를 선정 및 테이블에 추가
- referenceCount를 기준으로 (참조 수) 인기 순위 정렬
<br>
- 해당 코드를 참고해서 추천 배치를 만들어주시면 되겠습니다. @Uknow928  ^^7
=> 357 인기 장소 선정을 위한 배치 프로세스 추가

backend/place-region-batch/src/main/java/kr/co/yigil/BatchApplication.java, backend/place-region-batch/src/main/java/kr/co/yigil/batch/job/PopularPlaceJobConfig.java, backend/place-region-batch/src/main/java/kr/co/yigil/batch/job/UpdateRegionJobConfig.java, backend/support/domain/src/main/java/kr/co/yigil/member/repository/MemberRepository.java, backend/support/domain/src/main/java/kr/co/yigil/place/domain/PopularPlace.java, backend/support/domain/src/main/java/kr/co/yigil/place/infrastructure/PopularPlaceRepository.java, backend/support/domain/src/main/java/kr/co/yigil/travel/infrastructure/SpotRepository.java, backend/yigil-api/src/main/java/kr/co/yigil/login/infrastructure/GoogleLoginStrategy.java, backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberReader.java, backend/yigil-api/src/main/java/kr/co/yigil/member/infrastructure/MemberReaderImpl.java, backend/yigil-api/src/test/java/kr/co/yigil/login/infrastructure/GoogleLoginStrategyTest.java, backend/yigil-api/src/test/java/kr/co/yigil/member/infrastructure/MemberReaderImplTest.java
- 기존 구글 로그인 시, 소셜 로그인 인증 ID가 구글 서비스 내부적으로 변경사항이 생기는 오류를 발견했습니다.
- 그에따라 로그인 기준을 소셜 로그인 인증 ID가 아닌 이메일 기준으로 변경합니다.
<br>
- 구글 로그인 로직 변경 (쿼리)
<br>
- 테스트를 위해 빠른 리뷰 부탁드립니다.
=> HotFix: 구글 로그인 로직 수정

frontend/src/app/_components/header/Header.tsx, frontend/src/app/_components/header/HeaderClient.tsx, frontend/src/mocks/api/data/myPlaceData.ts, frontend/src/types/response.ts
도커 빌드 시 기존에 수정하거나 삭제했던 파일이나 타입이 남아있어 에러가 나는 상황을 수정했습니다. 
`TMyInfo` 타입을 `export` 해서 헤더에서 사용하도록 수정했습니다.
<br>
<br>
=> Hotfix type

.github/workflows/dev-backend-cd.yml, .github/workflows/prod-backend-cd.yml
docker-compose 설치가 되지 않아 기존 docker 사용을 위해 기존 docker-compose 삭제 및 docker로 수정함.
<br>
secret 값 추가 및 적용
<br>
=> Ci   cd 수정

frontend/src/app/_components/api/action.ts, frontend/src/app/endpoints/api/auth/callback/google/route.ts, frontend/src/app/endpoints/api/auth/callback/kakao/route.ts, frontend/src/types/response.ts
=> hotfix: 빌드 중에 에러난 route의 로그인 함수와 TMyInfo 타입 수정

backend/place-region-batch/src/main/java/kr/co/yigil/BatchApplication.java, backend/place-region-batch/src/main/java/kr/co/yigil/batch/job/DemographicPlaceJobConfig.java, backend/place-region-batch/src/main/java/kr/co/yigil/batch/job/PopularPlaceJobConfig.java, backend/support/domain/src/main/java/kr/co/yigil/place/domain/DemographicPlace.java, backend/support/domain/src/main/java/kr/co/yigil/place/infrastructure/DemographicPlaceRepository.java, backend/support/domain/src/main/java/kr/co/yigil/travel/infrastructure/SpotRepository.java, backend/yigil-api/src/main/java/kr/co/yigil/place/application/PlaceFacade.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceReader.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceService.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/infrastructure/PlaceReaderImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/controller/PlaceApiController.java, backend/yigil-api/src/test/java/kr/co/yigil/place/application/PlaceFacadeTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/domain/PlaceServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/infrastructure/PlaceReaderImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/interfaces/controller/PlaceApiControllerTest.java
성별나이대 별 인기 장소 선별 및 조회 기능 
<br>
- 성별,나이대 별 인기 장소 선별을 위한 배치잡 추가 (yml 파일 spring.batch.job.name: demographicPlaceJob 로 돌리면 될듯합니다)
- 성별,나이대 별 인기 장소 생성 및 조회 기능
<br>
=> 성별,나이대 별 인기 장소 선별 및 조회 기능

backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/controller/PlaceApiController.java
- 병합과정중 사라진 메서드를 복구합니다
<br>
- 메서드 복구 및 테스트로 검증 완료.
<br>
=> 394 hotfix missing method

backend/yigil-admin/src/main/java/kr/co/yigil/notice/domain/NoticeInfo.java, backend/yigil-admin/src/main/java/kr/co/yigil/notice/interfaces/dto/NoticeDto.java, backend/yigil-admin/src/main/java/kr/co/yigil/notice/interfaces/dto/mapper/NoticeMapper.java, backend/yigil-admin/src/test/java/kr/co/yigil/notice/interfaces/controller/NoticeApiControllerTest.java
=> notice list 형식 변경

backend/support/domain/src/main/java/kr/co/yigil/admin/domain/Admin.java, backend/yigil-admin/src/main/java/kr/co/yigil/admin/domain/admin/AdminInfo.java, backend/yigil-admin/src/main/java/kr/co/yigil/admin/domain/admin/AdminServiceImpl.java, backend/yigil-admin/src/main/java/kr/co/yigil/admin/domain/adminSignUp/AdminSignUpServiceImpl.java, backend/yigil-admin/src/main/java/kr/co/yigil/file/domain/FileUploadEvent.java, backend/yigil-admin/src/main/java/kr/co/yigil/file/infrastructure/FileUploaderImpl.java, backend/yigil-admin/src/test/java/kr/co/yigil/admin/domain/admin/AdminServiceImplTest.java, backend/yigil-api/src/main/java/kr/co/yigil/file/FileUploadEvent.java, backend/yigil-api/src/main/java/kr/co/yigil/file/infrastructure/FileUploaderImpl.java
admin 프로필이미지 필드 수정
<br>
String 형식의 url 에서 AttachFile type 으로 필드 수정
<br>
=> refactor : admin 프로필이미지 필드 수정

backend/support/domain/src/main/java/kr/co/yigil/notice/domain/Notice.java, backend/yigil-admin/src/main/java/kr/co/yigil/notice/domain/NoticeInfo.java
=> hotfix : notice의 작성자 이미지 로직 변경

backend/support/domain/src/main/java/kr/co/yigil/notice/domain/Notice.java
=> hotfix: 진짜 최종. 프로필 이미지

frontend/src/app/(with-header)/(home)/page.tsx, frontend/src/app/(with-header)/(home)/places/regions/[id]/page.tsx, frontend/src/app/_components/place/Places.tsx, frontend/src/app/_components/place/PopularPlaces.tsx, frontend/src/app/_components/place/RegionPlaces.tsx, frontend/src/app/_components/place/RegionSelect.tsx
관심 지역 더보기 화면에 지역 선택 UI가 뜨지 않고, 홈 화면에서 선택되었던 지역이 더보기에서 반영되지 않던 오류를 수정합니다.
- Dynamic route를 활용해 관심 지역 더보기 화면에 홈 화면의 지역 선택이 반영되도록 구현하였습니다.
- 관심 지역 더보기 화면에 지역 선택 UI를 추가하였습니다.
=> 관심 지역 더보기 화면이 올바르게 뜨지 않던 오류 수정

backend/support/domain/src/main/java/kr/co/yigil/place/infrastructure/PlaceRepository.java, backend/yigil-api/src/docs/asciidoc/place-api.adoc, backend/yigil-api/src/main/java/kr/co/yigil/place/application/PlaceFacade.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceReader.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceService.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/infrastructure/PlaceReaderImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/controller/PlaceApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/dto/mapper/PlaceMapper.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/dto/response/PlaceKeywordResponse.java, backend/yigil-api/src/main/resources/application.yml, backend/yigil-api/src/test/java/kr/co/yigil/place/application/PlaceFacadeTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/domain/PlaceServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/infrastructure/PlaceReaderImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/interfaces/controller/PlaceApiControllerTest.java
- 장소 검색 시 검색어 추천을 위한 API를 작성합니다.
<br>
- 검색어 추천을 기능 API 추가
- 테스트 코드 및 API 문서 작성
<br>
=> feat: 검색어 추천 기능 API 추가

backend/support/domain/src/main/java/kr/co/yigil/place/infrastructure/PlaceRepository.java, backend/yigil-api/src/docs/asciidoc/place-api.adoc, backend/yigil-api/src/main/java/kr/co/yigil/favor/domain/FavorReader.java, backend/yigil-api/src/main/java/kr/co/yigil/favor/domain/FavorServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/favor/domain/repository/FavorRepository.java, backend/yigil-api/src/main/java/kr/co/yigil/favor/infrastructure/FavorReaderImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/global/exception/ExceptionCode.java, backend/yigil-api/src/main/java/kr/co/yigil/place/application/PlaceFacade.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceReader.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceService.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/infrastructure/PlaceReaderImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/controller/PlaceApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/dto/mapper/PlaceMapper.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/dto/response/PlaceKeywordResponse.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/application/CourseFacade.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/controller/CourseApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/response/CourseSearchResponse.java, backend/yigil-api/src/main/resources/application.yml, backend/yigil-api/src/test/java/kr/co/yigil/favor/domain/FavorServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/favor/infrastructure/FavorReaderImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/application/PlaceFacadeTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/domain/PlaceServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/infrastructure/PlaceReaderImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/interfaces/controller/PlaceApiControllerTest.java
- 좋아요 도메인에서 발생한 오류를 수정합니다.
<br>
- 좋아요 예외 처리 로직 추가
- 좋아요 삭제(취소) 로직 변경
<br>
=> 421 hotfix 좋아요 중첩시 예외 처리가 제대로 안되는 오류 수정

backend/support/domain/src/main/java/kr/co/yigil/global/SortBy.java, backend/yigil-admin/src/main/java/kr/co/yigil/notice/interfaces/controller/NoticeApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/interfaces/controller/BookmarkApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/comment/interfaces/controller/CommentApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/interfaces/controller/NotificationApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/controller/CourseApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/controller/SpotApiController.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/CourseApiControllerTest.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/SpotApiControllerTest.java
=> hotfix: sortby 카멜 케이스 스네이크 케이스 관련 변경사항 누락된 것 수정

.github/workflows/dev-frontend-cd.yml
=> frontend 배포 테스트

.github/workflows/dev-frontend-cd.yml
=> frontend 배포 테스트 2

backend/support/domain/src/main/java/kr/co/yigil/travel/infrastructure/SpotRepository.java, backend/yigil-admin/src/main/resources/application.yml, backend/yigil-api/src/main/java/kr/co/yigil/travel/infrastructure/spot/SpotReaderImpl.java, backend/yigil-api/src/main/resources/application.yml, backend/yigil-api/src/test/java/kr/co/yigil/travel/infrastructure/spot/SpotReaderImplTest.java
=> 436 hotfix 하나의 장소에 여러 spot이 추가되있는 경우 오류가 나는 현상 수정

backend/yigil-api/src/main/resources/static/docs/course-api.html, backend/yigil-api/src/main/resources/static/docs/index.html, backend/yigil-api/src/main/resources/static/docs/member-api.html, backend/yigil-api/src/main/resources/static/docs/notification-api.html, backend/yigil-api/src/main/resources/static/docs/place-api.html, backend/yigil-api/src/test/java/kr/co/yigil/member/domain/MemberServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/member/interfaces/controller/MemberApiControllerTest.java
=> 응답 객체 변경에 따른 테스트, api 문서 업데이트

backend/support/domain/src/main/java/kr/co/yigil/member/Member.java, backend/support/domain/src/main/java/kr/co/yigil/region/domain/Region.java, backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberServiceImpl.java
=> Fix member update

.github/workflows/prod-backend-cd.yml, backend/support/domain/src/main/java/kr/co/yigil/travel/infrastructure/SpotRepository.java, backend/yigil-api/src/main/generated/kr/co/yigil/place/interfaces/dto/mapper/PlaceMapperImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/global/exception/ExceptionCode.java, backend/yigil-api/src/main/java/kr/co/yigil/place/application/PlaceFacade.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceService.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/controller/PlaceApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/dto/mapper/PlaceMapper.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/dto/response/PlaceStaticImageResponse.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotReader.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/infrastructure/spot/SpotReaderImpl.java, backend/yigil-api/src/test/java/kr/co/yigil/place/application/PlaceFacadeTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/domain/PlaceServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/interfaces/controller/PlaceApiControllerTest.java
📝Description
✅Task
✍️Additional
=> 469 place map static image

frontend/Dockerfile, frontend/package-lock.json, frontend/package.json
`Next.js`에서 이미지 최적화를 위해 사용을 권장하는 라이브러리 `sharp`가 적용되지 않던 문제를 해결합니다.
- [관련 해결책](https://github.com/lovell/sharp/issues/3877#issuecomment-1837594469)에 의거하여, `sharp` 라이브러리의 버전을 다운그레이드합니다.
=> Sharp 버전 다운그레이드

backend/support/domain/src/main/java/kr/co/yigil/member/Ages.java, backend/support/domain/src/main/java/kr/co/yigil/member/Gender.java, backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberInfo.java, backend/yigil-api/src/main/resources/static/docs/course-api.html, backend/yigil-api/src/main/resources/static/docs/index.html, backend/yigil-api/src/main/resources/static/docs/notification-api.html, backend/yigil-api/src/main/resources/static/docs/place-api.html
한글로 요청을 보낼 시 업데이트가 잘 되지 않는 문제가 있어서
업데이트 내용을 male/female, 10, 20, 30 등으로 요청할 수 있도록 변경
<br>
<br>
=> member udpate 성별, 나이 수정

backend/yigil-api/src/main/generated/kr/co/yigil/bookmark/interfaces/dto/mapper/BookmarkMapperImpl.java, backend/yigil-api/src/main/generated/kr/co/yigil/comment/interfaces/dto/mapper/CommentMapperImpl.java, backend/yigil-api/src/main/generated/kr/co/yigil/favor/interfaces/dto/mapper/FavorMapperImpl.java, backend/yigil-api/src/main/generated/kr/co/yigil/follow/interfaces/dto/FollowDtoMapperImpl.java, backend/yigil-api/src/main/generated/kr/co/yigil/login/interfaces/dto/mapper/LoginMapperImpl.java, backend/yigil-api/src/main/generated/kr/co/yigil/member/interfaces/dto/mapper/MemberDtoMapperImpl.java, backend/yigil-api/src/main/generated/kr/co/yigil/notification/interfaces/dto/mapper/NotificationMapperImpl.java, backend/yigil-api/src/main/generated/kr/co/yigil/place/interfaces/dto/mapper/PlaceMapperImpl.java, backend/yigil-api/src/main/generated/kr/co/yigil/region/interfaces/dto/mapper/RegionMapperImpl.java, backend/yigil-api/src/main/generated/kr/co/yigil/travel/interfaces/dto/mapper/CourseMapperImpl.java, backend/yigil-api/src/main/generated/kr/co/yigil/travel/interfaces/dto/mapper/SpotMapperImpl.java, backend/yigil-api/src/main/generated/kr/co/yigil/travel/interfaces/dto/mapper/TravelMapperImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/response/MySpotsResponseDto.java, backend/yigil-api/src/main/resources/static/docs/course-api.html, backend/yigil-api/src/main/resources/static/docs/index.html, backend/yigil-api/src/main/resources/static/docs/notification-api.html, backend/yigil-api/src/main/resources/static/docs/place-api.html, backend/yigil-api/src/main/resources/static/docs/spot-api.html, backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/SpotApiControllerTest.java
내 스팟들 정보에서 place id 를 추가
<br>
- my spot list 조회시 응답에 place의 id를 추가하였습니다.
<br>
- 동작 테스트, 단위 테스트, 문서 업데이트 수행하였습니다.
=> 484 add place Id to my spot list 

backend/yigil-api/src/main/java/kr/co/yigil/global/config/RedisConfig.java
=> hotfix redis

backend/support/domain/src/main/java/kr/co/yigil/member/Ages.java, backend/support/domain/src/main/java/kr/co/yigil/member/Gender.java, backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberInfo.java
=> hotfix mypage

backend/support/domain/src/main/java/kr/co/yigil/member/Ages.java, backend/support/domain/src/main/java/kr/co/yigil/member/Gender.java, backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberInfo.java
<br>
- 성별, 젠더 응답 변경
- favorite regions의 지역 이름 변경 
<br>
=> 515 hotfix gender age change response

backend/yigil-api/src/main/resources/logback-spring.xml
=> logback test

backend/support/domain/src/main/java/kr/co/yigil/region/domain/Region.java, backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/region/domain/RegionInfo.java, backend/yigil-api/src/test/java/kr/co/yigil/member/domain/MemberServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/member/interfaces/controller/MemberApiControllerTest.java
=> member 리전 정보 업데이트 및 프로필 이미지 변경 테스트 코드 보완

backend/support/domain/src/main/java/kr/co/yigil/member/Member.java, backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberCommand.java, backend/yigil-api/src/main/java/kr/co/yigil/member/interfaces/dto/MemberDto.java, backend/yigil-api/src/test/java/kr/co/yigil/member/domain/MemberServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/member/interfaces/controller/MemberApiControllerTest.java
<br>
- profile 이미지를 없앨 경우 isProfileEmpty 필드를 true로 설정하도록 변경
- 이미지가 널이 아니고 isProfileEmpty 필드가 true일 경우 예외 발생 
<br>
=> mypage profile image update 로직 수정

backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberServiceImpl.java, backend/yigil-api/src/test/java/kr/co/yigil/member/domain/MemberServiceImplTest.java
=> 532 hotifx member servier file 누락

backend/yigil-admin/src/main/java/kr/co/yigil/travel/spot/domain/SpotInfoDto.java, backend/yigil-admin/src/main/java/kr/co/yigil/travel/spot/interfaces/dto/SpotDto.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/infrastructure/NotificationSenderImpl.java
- 알림 구독을 확인하기 위해 로그 코드를 추가합니다.
<br>
- 빠른 병합 부탁드립니다 (해당 부분은 실제 운영 서버에 올라가지 않도록 해야합니다)
<br>
=> 알림 구독 확인 로그 (개발 서버용)

frontend/public/icons/logout.svg, frontend/src/app/_components/mypage/spot/MyPageSpotList.tsx, frontend/src/app/_components/ui/popover/constants.tsx
헤더의 로그아웃 아이콘 수정
마이페이지 스팟 햄버거 아이콘 클릭 시 나오는 X 아이콘 스타일 수정
<br>
<br>
=> hotfix: 디자인에 맞춰 꼭 수정 필요한 스타일 수정

frontend/src/app/_components/ui/button/ToPreviousPage.tsx, frontend/src/app/not-found.tsx
=> 404 페이지 작성

frontend/src/app/_components/add/common/AddPlaceInfo.tsx, frontend/src/app/_components/mypage/spot/MyPageSpotItem.tsx, frontend/src/app/_components/place/Place.tsx
place 이름 컨테이너 사이즈보다 넘치는 현상 수정.
장소 추가 시 장소 입력했을 때 이름 레이블 줄어들던 것 수정
<br>
<br>
=> hotfix: place의 장소 스타일 수정 및 장소 추가 시 장소 이름 스타일 수정

frontend/src/app/_components/ui/button/ToPreviousPage.tsx, frontend/src/app/not-found.tsx
=> Feat 404 page

frontend/src/app/_components/near/ViewTravelMap.tsx
피드백 받았던 주변 지도 이동 시에 로딩으로 드래그가 막히던 현상을 로딩 진행중에도 드래그 가능하도록 수정했습니다.
<br>
<br>
=> fix: 주변 지도 로딩 창 수정

frontend/src/app/_components/near/ViewTravelMap.tsx
=> Fix near map loading

frontend/src/app/_components/hooks/useIntersectionObserver.ts, frontend/src/app/_components/mypage/bookmark/MyPageBookmarkList.tsx
=> hotfix: 마이페이지 북마크 무한렌더링 수정

backend/yigil-admin/src/test/java/kr/co/yigil/travel/spot/domain/SpotServiceImplTest.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/application/NotificationFacade.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/domain/NotificationService.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/domain/NotificationServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/interfaces/controller/NotificationApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/interfaces/dto/request/NotificationReadRequest.java, backend/yigil-api/src/test/java/kr/co/yigil/notification/application/NotificationFacadeTest.java, backend/yigil-api/src/test/java/kr/co/yigil/notification/domain/NotificationServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/notification/interfaces/controller/NotificationApiControllerTest.java
<br>
- 알림 읽음 처리를 일괄로 처리할 수 있도록 api를 수정하였습니다.
- 테스트를 수정하였습니다.
<br>
=> 536 notification

backend/support/domain/src/main/java/kr/co/yigil/place/domain/Place.java, backend/support/domain/src/main/java/kr/co/yigil/travel/infrastructure/SpotRepository.java, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/domain/BookmarkInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/bookmark/domain/BookmarkServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceCacheReader.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceCacheStore.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceRateCalculator.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/infrastructure/PlaceCacheReaderImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/infrastructure/PlaceCacheStoreImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/infrastructure/PlaceRateCaculatorImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/infrastructure/PlaceRateCalculatorImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/infrastructure/PlaceReaderImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotCommand.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotReader.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/infrastructure/course/CourseSpotSeriesFactoryImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/infrastructure/spot/SpotReaderImpl.java, backend/yigil-api/src/test/java/kr/co/yigil/bookmark/infrastructure/BookmarkStoreImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/domain/PlaceServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/infrastructure/PlaceCacheReaderImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/infrastructure/PlaceCacheStoreImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/infrastructure/PlaceRateCalculatorImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/domain/spot/SpotServiceImplTest.java
=> 534 장소 별점 캐시

frontend/src/app/_components/ui/popover/constants.tsx
홈 페이지의 FAB에서 다시 코스 추가에 접근 가능하게 메뉴를 추가합니다.
=> 홈 FAB에 코스 추가 접근 가능한 메뉴 다시 넣기

frontend/src/app/_components/place/RegionSelect.tsx
장소 선택 UI의 개수/글자 길이가 길어질 때 쪼그라드는 현상을 수정합니다.
- 각 버튼이 줄어들지 않게 하고, 가려지는 UI는 캐러셀을 통해 탐색할 수 있도록 구현했습니다.
=> 장소 선택 UI에 캐러셀 적용

backend/support/domain/src/main/java/kr/co/yigil/travel/domain/Course.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/course/CourseCommand.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/course/CourseInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/course/CourseServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/infrastructure/course/CourseSeriesFactoryImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/CourseDetailInfoDto.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/mapper/CourseMapper.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/request/CourseUpdateRequest.java, backend/yigil-api/src/main/resources/static/docs/bookmark-api.html, backend/yigil-api/src/main/resources/static/docs/comment-api.html, backend/yigil-api/src/main/resources/static/docs/course-api.html, backend/yigil-api/src/main/resources/static/docs/favor-api.html, backend/yigil-api/src/main/resources/static/docs/follow-api.html, backend/yigil-api/src/main/resources/static/docs/index.html, backend/yigil-api/src/main/resources/static/docs/login-api.html, backend/yigil-api/src/main/resources/static/docs/member-api.html, backend/yigil-api/src/main/resources/static/docs/place-api.html, backend/yigil-api/src/main/resources/static/docs/region-api.html, backend/yigil-api/src/main/resources/static/docs/report-api.html, backend/yigil-api/src/main/resources/static/docs/spot-api.html, backend/yigil-api/src/main/resources/static/docs/travel-api.html, backend/yigil-api/src/test/java/kr/co/yigil/travel/domain/course/CourseServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/infrastructure/course/CourseSeriesFactoryImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/CourseApiControllerTest.java
<br>
- lineString 관련 수정
- 문서 업데이트
<br>
=> 598 코스 상세 조회 시 linestring 정보 전달

backend/place-region-batch/src/main/java/kr/co/yigil/batch/job/DailyRegionJobConfig.java, backend/place-region-batch/src/main/java/kr/co/yigil/batch/job/PopularPlaceJobConfig.java, backend/support/domain/src/main/java/kr/co/yigil/region/domain/DailyRegion.java, backend/support/domain/src/main/java/kr/co/yigil/region/infrastructure/DailyRegionRepository.java, backend/yigil-admin/src/main/java/kr/co/yigil/stats/application/StatsFacade.java, backend/yigil-admin/src/main/java/kr/co/yigil/stats/domain/StatsReader.java, backend/yigil-admin/src/main/java/kr/co/yigil/stats/domain/StatsService.java, backend/yigil-admin/src/main/java/kr/co/yigil/stats/domain/StatsServiceImpl.java, backend/yigil-admin/src/main/java/kr/co/yigil/stats/infrastructure/StatsReaderImpl.java, backend/yigil-admin/src/main/java/kr/co/yigil/stats/interfaces/controller/StatsApiController.java, backend/yigil-admin/src/main/java/kr/co/yigil/stats/interfaces/dto/mapper/StatsMapper.java, backend/yigil-admin/src/main/java/kr/co/yigil/stats/interfaces/dto/response/RegionStatsResponse.java, backend/yigil-admin/src/test/java/kr/co/yigil/stats/application/StatsFacadeTest.java, backend/yigil-admin/src/test/java/kr/co/yigil/stats/domain/StatsServiceImplTest.java, backend/yigil-admin/src/test/java/kr/co/yigil/stats/infrastructure/StatsReaderImplTest.java, backend/yigil-admin/src/test/java/kr/co/yigil/stats/interfaces/controller/StatsApiControllerTest.java
<br>
- 전일 통계 배치
- 어드민 통계 조회 api 
<br>
=> 608 전일 지역별 글 개수 통계용 배치

backend/support/domain/src/main/java/kr/co/yigil/travel/infrastructure/SpotRepository.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotReader.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/infrastructure/course/CourseSpotSeriesFactoryImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/infrastructure/spot/SpotReaderImpl.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/infrastructure/course/CourseSpotSeriesFactoryImplTest.java
<br>
- 코스 등록시 스팟의 권한 확인을 하여 본인의 스팟이 아니면 예외를 발생하도록 하였습니다.
<br>
=> course 생성시 spot의 권한 확인 로직 추가

backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/dto/PlaceDetailInfoDto.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/dto/mapper/PlaceMapper.java, backend/yigil-api/src/main/resources/static/docs/index.html, backend/yigil-api/src/main/resources/static/docs/place-api.html, backend/yigil-api/src/main/resources/static/docs/report-api.html, backend/yigil-api/src/test/java/kr/co/yigil/place/domain/PlaceServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/interfaces/controller/PlaceApiControllerTest.java
<br>
- place id로 조회하는 정보에 장소의 좌표값을 추가하였습니다. 
<br>
=> 629 place detail info에 장소의 좌표 포함하기

frontend/src/app/(with-header)/detail/[travel]/[id]/page.tsx, frontend/src/app/_components/mypage/course/CourseDetail.tsx, frontend/src/app/_components/mypage/spot/SpotDetail.tsx, frontend/src/types/myPageResponse.ts
기존에 그냥 로그인 한 것만 체크하던 로직에서 로그인과, 로그인한 유저의 spot / course인지 검증하는 로직을 추가했습니다.
<br>
<br>
=> 내 스팟, 코스가 아니어도 나오던 수정 버튼 수정

frontend/src/app/(with-header)/detail/[travel]/[id]/page.tsx, frontend/src/app/_components/mypage/course/CourseDetail.tsx, frontend/src/app/_components/mypage/spot/SpotDetail.tsx, frontend/src/types/myPageResponse.ts
=> spot/course detail 수정 디벨롭 병합

backend/place-region-batch/src/main/java/kr/co/yigil/batch/job/DailyTotalFavorCountJobConfig.java, backend/support/domain/src/main/java/kr/co/yigil/follow/domain/Follow.java, backend/support/domain/src/main/java/kr/co/yigil/global/SortBy.java
<br>
- 쿼리에 날짜 조건을 담은 변수를 삽입하지 않아 배치가 잘 돌아가지 않는 문제를 수정하였습니다.
<br>
=> hotfix TotalFavorCount 배치 수정

backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/dto/PlaceCoordinateDto.java, backend/yigil-api/src/test/java/kr/co/yigil/notification/interfaces/controller/NotificationApiControllerTest.java
- 테스트시 발생하는 에러를 수정합니다.
<br>
<br>
=> [hotfix] fix error with test

backend/yigil-api/src/main/java/kr/co/yigil/report/report/interfaces/controller/ReportApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/course/CourseInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/course/CourseServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/controller/CourseApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/CourseInfoDto.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/SpotInfoDto.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/mapper/CourseMapper.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/mapper/SpotMapper.java, backend/yigil-api/src/main/resources/static/docs/course-api.html, backend/yigil-api/src/main/resources/static/docs/index.html, backend/yigil-api/src/main/resources/static/docs/notification-api.html, backend/yigil-api/src/main/resources/static/docs/report-api.html, backend/yigil-api/src/main/resources/static/docs/spot-api.html, backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/CourseApiControllerTest.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/SpotApiControllerTest.java
장소 내 spot 과 course에 사용자의 작성자 following 여부를 추가하였습니다.
<br>
<br>
=> 635 place in course

backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/SpotInfoDto.java, backend/yigil-api/src/main/resources/static/docs/course-api.html, backend/yigil-api/src/main/resources/static/docs/index.html, backend/yigil-api/src/main/resources/static/docs/report-api.html, backend/yigil-api/src/main/resources/static/docs/spot-api.html, backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/SpotApiControllerTest.java
장소 내 spot의 image url들이 잘 매핑되지 않는 문제 해결 
<br>
<br>
=> fix spot in place  image mapping problem

backend/support/domain/src/main/java/kr/co/yigil/place/infrastructure/PlaceRepository.java, backend/support/domain/src/main/java/kr/co/yigil/travel/infrastructure/SpotRepository.java, backend/yigil-api/src/main/java/kr/co/yigil/global/exception/GlobalExceptionHandler.java, backend/yigil-api/src/main/java/kr/co/yigil/place/application/PlaceFacade.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceReader.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceService.java, backend/yigil-api/src/main/java/kr/co/yigil/place/domain/PlaceServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/controller/PlaceApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/place/interfaces/dto/response/MyPlaceIdResponse.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotReader.java, backend/yigil-api/src/main/java/kr/co/yigil/travel/infrastructure/spot/SpotReaderImpl.java, backend/yigil-api/src/test/java/kr/co/yigil/place/application/PlaceFacadeTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/domain/PlaceServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/place/interfaces/controller/PlaceApiControllerTest.java, backend/yigil-api/src/test/java/kr/co/yigil/travel/infrastructure/spot/SpotReaderImplTest.java
- #656 에 따라 사용자가 작성한 리뷰를 가진 place id를 조회하는 api를 추가합니다
<br>
- api추가 및 테스트 코드로 검증 (추가적인 join쿼리를 막기위해 @Query를 사용하였습니다)
<br>
=> 656 사용자의 place id를 조회하는 api 생성

backend/support/domain/src/main/java/kr/co/yigil/notification/domain/Notification.java, backend/support/domain/src/main/java/kr/co/yigil/notification/infrastructure/NotificationRepository.java, backend/yigil-admin/src/main/java/kr/co/yigil/notification/domain/NotificationFactory.java, backend/yigil-admin/src/main/java/kr/co/yigil/notification/infrastructure/NotificationReaderImpl.java, backend/yigil-api/src/docs/asciidoc/follow-api.adoc, backend/yigil-api/src/docs/asciidoc/notification-api.adoc, backend/yigil-api/src/main/java/kr/co/yigil/notification/application/NotificationFacade.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/domain/NotificationFactory.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/domain/NotificationInfo.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/domain/NotificationService.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/domain/NotificationServiceImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/infrastructure/NotificationReaderImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/infrastructure/NotificationSenderImpl.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/interfaces/controller/NotificationApiController.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/interfaces/dto/NotificationInfoDto.java, backend/yigil-api/src/main/java/kr/co/yigil/notification/interfaces/dto/mapper/NotificationMapper.java, backend/yigil-api/src/main/resources/static/docs/course-api.html, backend/yigil-api/src/main/resources/static/docs/follow-api.html, backend/yigil-api/src/main/resources/static/docs/index.html, backend/yigil-api/src/main/resources/static/docs/notification-api.html, backend/yigil-api/src/main/resources/static/docs/report-api.html, backend/yigil-api/src/main/resources/static/docs/spot-api.html, backend/yigil-api/src/test/java/kr/co/yigil/notification/application/NotificationFacadeTest.java, backend/yigil-api/src/test/java/kr/co/yigil/notification/domain/NotificationServiceImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/notification/infrastructure/NotificationReaderImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/notification/infrastructure/NotificationStoreImplTest.java, backend/yigil-api/src/test/java/kr/co/yigil/notification/interfaces/controller/NotificationApiControllerTest.java
알림 목록에 발신자의 프로필 이미지와 아이디를 추가하였습니다.
<br>
<br>
- 머지되면 데이터베이스를 변경해야 합니다.
=> notification api 수정 

backend/support/domain/src/main/java/kr/co/yigil/member/repository/MemberRepository.java, backend/yigil-api/src/main/java/kr/co/yigil/global/exception/ExceptionCode.java, backend/yigil-api/src/main/java/kr/co/yigil/login/infrastructure/GoogleLoginStrategy.java, backend/yigil-api/src/main/java/kr/co/yigil/login/infrastructure/KakaoLoginStrategy.java, backend/yigil-api/src/main/java/kr/co/yigil/login/infrastructure/NaverLoginStrategy.java, backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberReader.java, backend/yigil-api/src/main/java/kr/co/yigil/member/infrastructure/MemberReaderImpl.java
- 회원가입 시 중복된 이메일로 회원가입을 시도하는 경우 발생하는 에러를 핸들링합니다
<br>
- 에러 검증을 위한 validation 로직 추가
- 예외 코드 추가 및 예외 처리 로직
<br>
=> add validate when new member request signup

frontend/src/app/_components/mypage/MyPageInfo.tsx
'네이버 아이디로 로그인(네아로)' 검수 요청을 위한 요구사항을 만족하도록 화면에 표시되는 데이터를 수정합니다.
- 마이페이지 화면에 사용자의 이메일이 표시되도록 수정합니다.
=> 네아로 요구사항 만족을 위한 화면 표시 데이터 수정

frontend/next.config.js
기본 이미지 보이지 않는 현상 수정을 위한 설정 파일 수정입니다.
<br>
<br>
=> hotfix: naver 기본 이미지 config 설정

frontend/src/app/_components/ui/button/GoogleLoginButton.tsx
=> hotfix: 구글 로그인 수정

frontend/src/app/_components/ui/button/GoogleLoginButton.tsx
=> Hotfix google login 디벨롭 병합

backend/support/domain/src/main/java/kr/co/yigil/follow/domain/Follow.java, backend/support/domain/src/main/java/kr/co/yigil/global/SortBy.java, backend/yigil-api/src/main/java/kr/co/yigil/follow/interfaces/controller/FollowApiController.java, backend/yigil-api/src/main/resources/static/docs/course-api.html, backend/yigil-api/src/main/resources/static/docs/follow-api.html, backend/yigil-api/src/main/resources/static/docs/index.html, backend/yigil-api/src/main/resources/static/docs/notification-api.html, backend/yigil-api/src/main/resources/static/docs/report-api.html, backend/yigil-api/src/main/resources/static/docs/spot-api.html, backend/yigil-api/src/test/java/kr/co/yigil/follow/interfaces/controller/FollowApiControllerTest.java
<br>
- follower와 following member의 nickname 으로 정렬할 수 있도록 하였습니다.
<br>
=> follow 정렬 옵션 추가

frontend/src/app/_components/add/course/without-new/AddCourseExistSpots.tsx
작성한 장소 리뷰가 없는 경우에 대한 예외 처리 코드를 작성합니다.
- 작성한 장소 리뷰가 없는 경우 안내 문구를 표시합니다.
- 정확히는 불러온 장소 리뷰가 0개인 경우이며, 장소 리뷰 불러오기에 실패했을 때도 마찬가지 문구가 표시됩니다. 다만 그 때는 별도의 토스트가 뜨게 됩니다.
=> 작성한 장소 리뷰가 없는 경우 안내 문구 표시

frontend/package-lock.json, frontend/package.json, frontend/src/app/(with-header)/place/[id]/@reviews/action.ts, frontend/src/app/(with-header)/place/[id]/@reviews/courses/page.tsx, frontend/src/app/(with-header)/place/[id]/@reviews/page.tsx, frontend/src/app/_components/place/ReportButton.tsx, frontend/src/app/_components/place/course/Course.tsx, frontend/src/app/_components/place/spot/Spot.tsx, frontend/src/app/_components/place/spot/Spots.tsx, frontend/src/app/_components/ui/ReportRadioGroup.tsx, frontend/src/app/_components/ui/dialog/ReportDialog.tsx, frontend/src/context/ReportContext.tsx, frontend/src/types/response.ts
Spot/Course를 신고하는 기능을 추가합니다.
- 신고를 위한 UI인 다이얼로그를 구현했습니다.
- 백엔드 API를 통해 신고하는 기능을 구현했습니다.
=> Spot/Course 신고 기능 추가

frontend/src/app/_components/reaction/Comment.tsx, frontend/src/app/_components/reaction/MoreButton.tsx
댓글을 신고하는 기능을 추가합니다.
- 더보기 버튼을 눌러 확인할 수 있는 댓글 신고하기 버튼을 눌러서 댓글을 신고하는 기능을 추가합니다.
=> 댓글 신고 기능 추가

frontend/src/app/_components/mypage/course/CourseDetail.tsx
=> Mypage like 재 Pr

frontend/src/app/_components/course/Course.tsx, frontend/src/app/_components/place/course/Course.tsx
코스 관련 컴포넌트에 붙은 링크를 수정합니다.
- 코스 검색 결과 링크 수정
- 장소 상세 화면 내 코스 목록에서 코스 상세 기록 화면으로 접근 가능한 링크 추가
=> 코스 관련 링크 수정

frontend/src/app/(with-header)/(mypage)/mypage/favorite/course/page.tsx
좋아요 한 코스가 없을 경우 빈 화면이 나와서 그에 대한 글씨 처리했습니다.
<br>
<br>
=> fix: 좋아요 한 코스 없을 경우 처리

frontend/src/app/(with-header)/layout.tsx, frontend/src/app/_components/notification/NotificationIcon.tsx, frontend/src/context/NextPublicContext.tsx
=> fix: 알림 요청 api url 수정

frontend/src/app/_components/add/course/AddCourseSpotData.tsx, frontend/src/app/_components/add/course/without-new/ExistPlaceItem.tsx, frontend/src/context/travel/course/reducer.ts, frontend/src/context/travel/schema.ts, frontend/src/types/response.ts
=> 기존 장소 데이터 형식 오류 수정

frontend/src/app/_components/mypage/spot/MyPageSpotItem.tsx, frontend/src/types/myPageResponse.ts
=> fix: 마이페이지 date 컬럼 타입 수정

frontend/src/app/_components/add/course/without-new/ExistPlaceItem.tsx, frontend/src/app/_components/notification/NotificationIcon.tsx
=> fix: 빌드 에러 수정

frontend/src/app/_components/add/course/without-new/AddCourseOrder.tsx, frontend/src/app/_components/add/course/without-new/SortableSpotItem.tsx, frontend/src/app/_components/images/ImageItem.tsx, frontend/src/app/_components/images/ImagesContainer.tsx, frontend/src/app/_components/mypage/course/CourseDetail.tsx, frontend/src/app/_components/mypage/course/CourseSpotContainer.tsx, frontend/src/app/_components/mypage/course/CourseSpotItem.tsx
=> Hotfix drag

frontend/src/app/(with-header)/(mypage)/mypage/favorite/spot/page.tsx, frontend/src/app/_components/mypage/favorite/FavoriteActions.ts, frontend/src/app/_components/mypage/favorite/FavoriteCourseList.tsx, frontend/src/app/_components/mypage/favorite/FavoriteSpotItem.tsx, frontend/src/app/_components/mypage/favorite/FavoriteSpotList.tsx, frontend/src/types/myPageResponse.ts
좋아요의 장소를 구현했습니다.
장소의 이름을 클릭할 경우, 작성한 스팟 상세로 이동하게 됩니다.
<br>
<br>
현재 정렬했을 때 새로운 값이 오기는 하는데 정렬 기준이 바뀌지는 않는 것 같습니다..!
혹시 제가 못 일어나면 정욱님 오전에 백엔드분들과 정합 한 번 맞춰주시면 감사할 것 같아요!
=> feat: 좋아요 장소 구현

frontend/src/app/(with-header)/(home)/nearby/page.tsx, frontend/src/app/(with-header)/(mypage)/mypage/favorite/course/page.tsx, frontend/src/app/(with-header)/area/error.tsx, frontend/src/app/(with-header)/area/page.tsx, frontend/src/app/_components/mypage/MyPageSelectBtns.tsx, frontend/src/app/_components/mypage/bookmark/BookmarkList.tsx, frontend/src/app/_components/mypage/bookmark/bookmarkActions.ts, frontend/src/app/_components/mypage/course/CourseDetail.tsx, frontend/src/app/_components/mypage/course/MyPageCourseList.tsx, frontend/src/app/_components/mypage/favorite/FavoriteActions.ts, frontend/src/app/_components/mypage/favorite/FavoriteCourseList.tsx, frontend/src/app/_components/mypage/favorite/FavoriteSpotList.tsx, frontend/src/app/_components/mypage/follow/MyPageFollowList.tsx, frontend/src/app/_components/mypage/hooks/followActions.ts, frontend/src/app/_components/mypage/hooks/myPageActions.ts, frontend/src/app/_components/mypage/spot/MyPageSpotList.tsx, frontend/src/app/_components/near/hooks/nearActions.ts, frontend/src/app/_components/notification/Notification.tsx, frontend/src/app/_components/notification/NotificationItem.tsx, frontend/src/app/_components/notification/NotificationList.tsx, frontend/src/app/_components/notification/notificationActions.ts, frontend/src/app/_components/setting/ModifyUser.tsx, frontend/src/app/_components/setting/actions.ts, frontend/src/app/_components/setting/area/AreaItem.tsx, frontend/src/app/_components/setting/area/AreaList.tsx, frontend/src/app/_components/setting/area/actions.ts, frontend/src/app/notification/page.tsx
#655 pr 리뷰에서 남겨주셨던 `TBackendRequestResult` 타입을 사용해 fetch 함수들의 리턴 타입을 수정하였고 그에 따라 사용하는 곳에서의 로직도 수정했습니다.
<br>
<br>
실제 화면에 나타나는 결과와 차이가 나지는 않지만, 리턴 타입을 명시함으로써 사용하는 곳에서 fetch 함수가 어떤 값을 리턴하는지 명확하게 알 수 있도록 합니다.
=> fix: fetch 함수에 대한 리턴 타입 공통 타입으로 수정

frontend/src/app/(without-header)/login/page.tsx, frontend/src/app/endpoints/api/auth/callback/naver/route.ts, frontend/src/types/type.d.ts
=> chore: 네이버 환경변수 변경

frontend/src/app/_components/search/action.ts
=> fix: 수정 필요한 부분 추가 수정
