backend/src/main/java/kr/co/yigil/global/exception/InvalidTokenException.java
backend/src/main/java/kr/co/yigil/login/application/strategy/GoogleLoginStrategy.java
backend/src/main/java/kr/co/yigil/login/application/strategy/KakaoLoginStrategy.java
backend/src/main/java/kr/co/yigil/login/application/strategy/LoginStrategy.java
backend/src/main/java/kr/co/yigil/login/dto/request/KakaoLoginRequest.java
backend/src/main/java/kr/co/yigil/login/dto/response/KakaoTokenInfoResponse.java
backend/src/main/resources/url.properties

카카오 로그인을 위한 토큰 인증 로직을 추가하였습니다
#49 
호윤님 잘 부탁드립니다 @Uknow928

카카오 로그인을 위한 토큰 유효성 검사 로직 구현

---

backend/build.gradle
backend/src/main/java/kr/co/yigil/follow/application/FollowService.java
backend/src/main/java/kr/co/yigil/follow/domain/Follow.java
backend/src/main/java/kr/co/yigil/follow/domain/FollowCount.java
backend/src/main/java/kr/co/yigil/follow/domain/repository/FollowCountRedisRepository.java
backend/src/main/java/kr/co/yigil/follow/domain/repository/FollowCountRepository.java
backend/src/main/java/kr/co/yigil/follow/domain/repository/FollowRepository.java
backend/src/main/java/kr/co/yigil/follow/dto/response/FollowResponse.java
backend/src/main/java/kr/co/yigil/follow/dto/response/UnfollowResponse.java
backend/src/main/java/kr/co/yigil/follow/presentation/FollowController.java
backend/src/main/java/kr/co/yigil/global/config/RedisConfig.java
backend/src/main/java/kr/co/yigil/global/log/interceptor/ConnectionProxyHandler.java
backend/src/main/java/kr/co/yigil/member/domain/repository/MemberRepository.java
backend/src/main/java/kr/co/yigil/member/presentation/MemberController.java
backend/src/main/java/kr/co/yigil/notification/application/NotificationService.java
backend/src/main/java/kr/co/yigil/notification/domain/Notification.java
backend/src/main/java/kr/co/yigil/notification/domain/repository/NotificationRepository.java
backend/src/main/java/kr/co/yigil/notification/presentation/NotificationController.java
backend/src/main/java/kr/co/yigil/travel/domain/Travel.java
backend/src/test/java/kr/co/yigil/follow/application/FollowServiceTest.java
backend/src/test/java/kr/co/yigil/follow/presentation/FollowControllerTest.java
backend/src/test/java/kr/co/yigil/notification/application/NotificationServiceTest.java
backend/src/test/java/kr/co/yigil/notification/presentation/NotificationControllerTest.java

- 사용자 팔로우 팔로잉 기능 / 언팔로우 언팔로잉 기능 및 팔로우 시 실시간 알림 기능을 개발했습니다.
<br>
- 팔로우 팔로잉 기능을 위한 follow 도메인 및 기능 개발
- 성능 개선을 위한 팔로우 카운트 데이터를 캐싱 및 Redis에 저장
- 팔로우 발생 시 실시간 사용자에게 알림 생성 및 SSE / Spring-WebFlux / Reactor 를 활용한 알림 구독 기능 개발
<br>
- 리뷰 부탁드립니다.. (다음부턴 더 작은 단위로 Pr 날리도록 하겠습니다..)
- 프론트에서 SSE 이벤트 구독을 통한 실시간 알림 테스트가 필요합니다.

사용자 팔로우를 위한 api 및 sse를 통한 실시간 알림 기능 개발

---

backend/src/main/java/kr/co/yigil/follow/application/FollowRedisIntegrityService.java
backend/src/main/java/kr/co/yigil/follow/application/FollowService.java
backend/src/main/java/kr/co/yigil/follow/domain/repository/FollowRepository.java
backend/src/main/java/kr/co/yigil/follow/dto/FollowCountDto.java
backend/src/main/java/kr/co/yigil/global/config/JasyptConfig.java
backend/src/main/java/kr/co/yigil/member/application/MemberService.java
backend/src/main/java/kr/co/yigil/member/dto/response/MemberFollowerListResponse.java
backend/src/main/java/kr/co/yigil/member/dto/response/MemberFollowingListResponse.java
backend/src/main/java/kr/co/yigil/member/dto/response/MemberInfoResponse.java
backend/src/main/java/kr/co/yigil/member/presentation/MemberController.java
backend/src/test/java/kr/co/yigil/follow/application/FollowRedisIntegrityServiceTest.java
backend/src/test/java/kr/co/yigil/follow/application/FollowServiceTest.java
backend/src/test/java/kr/co/yigil/follow/domain/FollowCountTest.java
backend/src/test/java/kr/co/yigil/follow/domain/FollowTest.java
backend/src/test/java/kr/co/yigil/follow/domain/repository/FollowCountRedisRepositoryTest.java
backend/src/test/java/kr/co/yigil/global/config/AsyncConfigTest.java
backend/src/test/java/kr/co/yigil/global/config/JasyptConfigTest.java
backend/src/test/java/kr/co/yigil/member/application/MemberServiceTest.java
backend/src/test/java/kr/co/yigil/member/presentation/MemberControllerTest.java

- 팔로우 팔로워 리스트 조회를 위한 api를 만들었습니다 그리고 캐시 데이터베이스와 RDBMS 사이의 데이터 동기화 전략을 작성하였습니다.
<br>
- 팔로워 팔로잉 리스트 api 개설
- 레디스 동기화를 위한 서비스 레이어 (클래스) 추가
- 비즈니스로직 검증을 위한 테스트 작성
<br>
- 컨트롤러 테스트는 내일 수정하겠읍니다...
- api 명세서는 내일 작성하겠읍니다.
- 아~쌒으로 부탁드립니다.

사용자 팔로우 리스트 조회를 위한 api 및 redis 데이터 동기화 로직 작성

---

frontend/__mocks__/svg.js
frontend/__tests__/NavigationIcon.test.tsx
frontend/jest.config.ts
frontend/package-lock.json
frontend/package.json

- 프론트엔드 코드베이스에 단위 테스트 도구를 도입하여, 작성한 코드가 의도대로 동작하는지 검증할 수 있게 합니다.
- Jest와 React Testing Library, ts-node를 설치하였습니다.
- SVGR로 컴포넌트화한 SVG 파일도 Jest에서 해석할 수 있도록 Mock 파일을 작성하였습니다.
- Jest를 통해 비즈니스 로직이나 파생 상태 계산 함수가 올바르게 동작하는지 검증할 수 있습니다.
- Jest + React Testing Library를 통해 컴포넌트가 올바르게 렌더되었는지 검증할 수 있습니다.

Jest, React Testing Library 도입 및 첫 테스트 작성

---

backend/src/main/java/kr/co/yigil/file/FileUploadEvent.java
backend/src/test/java/kr/co/yigil/member/application/MemberServiceTest.java

- 테스트가 무한 실행되는 오류를 해결합니다.
<br>
- 테스트 코드 중 EventPublisher 객체를 적절히 모의처리하여 비동기 작업의 결과를 계속해서 기다리는 로직을 수정했습니다.
<br>
감사합니둥

fix issue that test does not complete

---

backend/build.gradle
backend/docker/postgreSQL/Dockerfile
backend/docker/postgreSQL/docker-compose.yml
backend/src/main/java/kr/co/yigil/follow/dto/response/FollowResponse.java
backend/src/main/java/kr/co/yigil/global/config/datasource/DataSourceType.java
backend/src/main/java/kr/co/yigil/global/config/datasource/MasterDataSourceConfig.java
backend/src/main/java/kr/co/yigil/global/config/datasource/SlaveDataSourceConfig.java
backend/src/main/java/kr/co/yigil/global/config/replication/ReplicationRoutingDataSource.java
backend/src/main/java/kr/co/yigil/global/config/replication/RoutingDataSourceConfig.java

- db 레플리케이션 구조를 적용하기 위해 설정 파일을 적용합니다.
<br>
- global/config 내의 설정 파일 생성 및 수정 (datasource, replication)
- application.yml 파일 구조 변경
<br>
- 해당 설정 적용 및 로컬에서도 db replication 을 성공 및 적용하셨다면 프로젝트는 잘 실행됩니다. (배포 서버의 설정을 변경해야 합니다.)
- @Transactional(readonly="true")설정이 있는 Service에서는 transaction 설정을 판별하여, Slave 로 요청을 보내게 됩니다 (읽기 전용)
- 해당 설정 방법은 위키에 작성해서 남겨놓겠습니다 :)

chore: add configuration for db replication

---

frontend/src/app/(without-header)/login/page.tsx
frontend/src/app/_components/ui/button/CloseButton.tsx

로고의 마진 속성을 픽셀로 지정했을 때 높이가 낮은 디바이스일 경우 로그인 버튼 뒷 배경이 제거되는 문제가 발생할 수 있어 스타일을 수정했습니다.
<br>
마진 속성이 아닌 로고와 로그인 버튼 등 각 태그의 높이 속성을 비율로 지정했습니다.
<br>
`CloseButton` 컴포넌트를 원래 제거하려고 했었으나 login의 page 자체는 서버 컴포넌트로 사용 중이기 때문에 따로 컴포넌트를 분리해 사용했습니다.

Login 페이지 스타일 수정

---

frontend/src/app/_components/add/common/InfoTitle.tsx

- #212 이슈에 따라 안내 문구 컴포넌트를 구현했습니다.
- props로 색상이 변경 될 `label`, 나머지 부가 글인 `addtionalLabel`, 글자 사이즈와 `line-height`을 설정하는 `textSizeAndLineHeight`, 폰트 굵기 설정하는 `fontBold`, 컴포넌트의 높이를 결정할 `height` 를 받습니다.
색상이 다른 글자와 검정 글자 부분이 첫 번째 줄에 함께 포함되어 있어 [slice](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/slice) 메서드를 사용했는데 좋은 방법인지 모르겠습니다. 혹시 생각하셨던 좋은 방법이 있을까요?☺️

안내 문구 컴포넌트 구현

---

frontend/src/app/_components/post/Post.tsx
frontend/src/app/_components/post/PostList.tsx

#216 PR에서 유실된 코드를 복원합니다.
추가로, Icon 렌더링 책임을 부모 컴포넌트가 가지도록 구조를 수정합니다.
- 사라졌던 `PostList` 컴포넌트 코드를 복원했습니다.
- Icon을 부모 컴포넌트에서 렌더링한 후, `ReactElement` 타입의 prop으로 내려주어 Icon별로 스타일을 지정할 수 있도록 변경하였습니다.
백엔드 PR 과정에서 유실된 코드가 있기 때문에, 해당 PR의 작업자인 @Uknow928 님을 리뷰어로 추가합니다. 해당 파일이 맞는지 여부만 확인해주시면 됩니다. @davidktlee 님께서는 refactor된 코드에 대해서 함께 확인해주시면 좋겠습니다.

백엔드 리팩토링 과정에서 유실된 코드 복원

---

frontend/public/icons/trash.svg
frontend/src/app/(with-header)/(home)/page.tsx
frontend/src/app/_components/FloatingActionButton.tsx
frontend/src/app/_components/ui/popover/PopOverItem.tsx
frontend/src/app/_components/ui/popover/constants.tsx
frontend/src/app/_components/ui/popover/types.ts

`FAB`가 범용 컴포넌트로써 동작하게 하기 위해 `FAB`에 들어가는 pop over data를 상위 컴포넌트에서 전달하는 방식으로 구조를 변경했습니다.
<br>
`FAB`를 여러 곳에서 호출, 사용하기 위해 pop over data를 props로 전달하는 방식으로 변경했습니다.
pop over icon의 스타일이 정해져있던 코드였는데 각 데이터를 전달할 때 스타일을 정의할 수 있게 코드 구조를 변경했습니다.
<br>
디자인이 자주 변경됨에 따라 코드가 자주 바뀌는 상황이긴 하지만 좀 더 범용성 높은 컴포넌트로 설계해 수정 공수 및 리뷰 공수가 적게 들게 노력해보겠습니다.

FAB 구조 변경 및 pop over data icon 타입 변경

---

frontend/src/app/_components/api/httpRequest.ts
frontend/src/app/endpoints/api/auth/[...nextauth]/route.ts

#235 이슈에서 언급했던 fetch 함수를 커링을 이용해 작성했습니다.
api 요청 함수를 사용하기 위해서는 여러 파라미터를 한 번에 받아야 하는 상황이 많은데,
커링 함수를 이용해 관심사 별로 분리가 가능하게 됨으로써 비슷한 로직을 가진 함수 임에도 매 번 많은 파라미터를 전달하지 않아도 되는 장점이 있습니다.
#205 현재는 환경 변수의 `base url`에 v1이라는 버전까지 명시가 되어 있는데 버전은 바뀔 가능성이 높으므로 환경 변수로 관리하지 않고 직접 작성하는 방식으로 바꿨습니다.
<br>
<br>
`next-auth`의 로그인 로직에서는 커링 함수로 작성한 fetch 로직이 잘 작동하지 않아 기존의 로직을 사용하는 것으로 해두었습니다.

api 요청 로직 작성

---

backend/support/domain/src/main/java/kr/co/yigil/travel/repository/SpotRepository.java
backend/yigil-api/src/main/java/kr/co/yigil/follow/application/FollowService.java
backend/yigil-api/src/main/java/kr/co/yigil/follow/domain/repository/FollowRepository.java
backend/yigil-api/src/main/java/kr/co/yigil/follow/dto/response/FollowerFindDto.java
backend/yigil-api/src/main/java/kr/co/yigil/follow/dto/response/FollowingFindDto.java
backend/yigil-api/src/main/java/kr/co/yigil/global/config/SecurityConfig.java
backend/yigil-api/src/main/java/kr/co/yigil/member/application/MemberService.java
backend/yigil-api/src/main/java/kr/co/yigil/member/presentation/MemberController.java
backend/yigil-api/src/main/java/kr/co/yigil/travel/application/SpotService.java

#224 프론트에서 작업 중인 mypage와 백엔드와 연결이 필요해 Member 도메인의 수정이 필요함. 
<br>
- 내 장소 조회를 slice 리스트로 보내도록 변경
- follow 목록 조회를 slice리스트로 보내도록 변경
- 위 변경사항을 위해 followerfinddto, followingfinddto 생성
- mypage에서 각각 course, spot, info, follower, following으로 api 호출 가능해짐
<br>
프론트와의 연결 확인해주시고 문제 있을 시 알려주시면 바로 수정하도록 하겠습니다!!

Member 도메인 수정 및 Follow Service 수정

---

frontend/src/app/(with-header)/(home)/page.tsx
frontend/src/app/_components/FloatingActionButton.tsx
frontend/src/app/_components/ui/popover/PopOver.tsx
frontend/src/app/_components/ui/popover/PopOverItem.tsx

#227 및 #247 에 의거하여, FAB와 PopOver를 수정합니다.
- 타깃 크기를 고려하여, `PopOverItem`에 padding을 주었습니다.
- PopOver 배경 클릭 시 이벤트가 backdrop에 propagate되어 PopOver가 닫히던 현장을 수정하였습니다.
- FAB의 아이콘을 외부에서 제공할 수 있도록 구조를 변경하였습니다.
- FAB의 아이콘은 `FloatingActionButton` 컴포넌트에서 관리되던 모달의 열림/닫힘 상태 변수 `isModalOpened`와 그 스타일이 강결합되어있는 상태였습니다. 따라서 모달이 열렸을 때와 닫혔을 때 두 가지 경우에 대한 아이콘 및 그 스타일을 지정해주어야 합니다.
- 서버 컴포넌트에서 클라이언트로 함수를 바로 넘겨줄 수 없기 때문에, 함수 컴포넌트 또한 바로 넘겨줄 수 없습니다. 따라서 FAB에 제공하는 icon prop들은 이미 렌더링이 끝난 `ReactElement` 타입이어야 합니다.

FAB 및 PopOver 수정

---

frontend/src/app/_components/add/AddSpot.tsx
frontend/src/app/_components/add/common/AddPlaceInto.tsx
frontend/src/app/_components/add/common/AddSpotMap.tsx
frontend/src/app/_components/add/common/PostRating.tsx
frontend/src/app/_components/add/common/PostReview.tsx
frontend/src/app/_components/add/common/index.ts
frontend/src/app/_components/add/common/step/StepNavigation.tsx
frontend/src/app/_components/images/ImageHandler.tsx
frontend/src/app/_components/images/ImagesContainer.tsx
frontend/src/app/_components/images/SortableItem.tsx
frontend/src/app/_components/images/index.ts
frontend/src/app/_components/naver-map/plusMarker.ts
frontend/src/app/_components/search/SearchBar.tsx
frontend/src/app/_components/search/SearchBox.tsx
frontend/src/app/_components/search/SearchResult.tsx

중간 배포를 위해 임시로 작업된 코드를 정리합니다.
- 여러 import 구문을 정리했습니다.
- Server Action 도입에 따라 달라져야 하는 부분에 JSDoc `@todo` 주석을 추가했습니다.
- 검색어 선택 시 마커를 찍도록 동작을 변경했습니다.
- 마커 선택 시 장소를 선택하도록 구현했습니다.
- 추가 플로우 첫 화면의 X 버튼을 누르면 이전 화면으로 돌아가도록 구현했습니다.
- 배포를 위해 추가된 프로덕션용 URL 선언을 제거하거나, 이후 Server Action 도입 후 `fetch` call과 함께 제거하기 쉽도록 위치를 옮겼습니다.
1. Map에 찍히는 마커는 검색 결과에서 새로운 결과를 선택할 때마다 바뀌어야 하는데, 잠깐 작동시켜보니 바뀌지 않는 문제가 있었습니다. 제 환경에서만 그런지 모르겠네요.
2. 마커 생성에 넘겨줄 장소 정보를 어떻게 관리해야할지 고민해봐야 합니다. 지금은 `AddSpot`, 즉 최상단 컴포넌트에서 props로 넘겨주고 있는데, drilling이 좀 심하게 일어나고 있는 것 같기도 해서 Context로 빼야하나 봐야할 거 같아요.

장소 추가 플로우 코드 수정

---

frontend/src/app/(with-header)/layout.tsx
frontend/src/app/_components/header/Header.tsx
frontend/src/app/_components/header/HeaderClient.tsx
frontend/src/app/endpoints/api/auth/[...nextauth]/route.ts
frontend/src/mocks/api/myPage.ts

유저 검증 api 를 `layout` 파일 호출 -> 클라이언트 호출로 변경
로그인 에러로 잘 동작하지 않는 부분이 있어 급하게 수정 후 pr 날립니다.
<br>
<br>
저는 로그인 후 쿠키를 브라우저에 저장시키고 다시 불러와서 사용하는 타이밍이 저장되는 타이밍보다 빠른 것으로 예상합니다.
예상되는 다른 의견 있으시면 댓글 남겨 주세용

hotfix: 로그인 후 헤더 레이아웃에서 api 호출 시 에러 나는 현상 수정

---

backend/yigil-api/src/docs/asciidoc/index.adoc
backend/yigil-api/src/docs/asciidoc/spot-api.adoc
backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/controller/SpotApiController.java
backend/yigil-api/src/main/resources/static/docs/index.html
backend/yigil-api/src/main/resources/static/docs/spot-api.html
backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/SpotApiControllerTest.java

- API 문서 자동화를 위해 Spring Rest Docs를 적용합니다.
<br>
- Spring Rest Docs 의존성 추가 및 gradle 작업 추가
- 예시 Test 코드 첨부 (SpotApiControllerTest)
- 예시 문서 첨부 (spots.adoc)
<br>
- 테스트 코드 같은 방법으로 검증하시고 문서 작업하실때 불러주시면 방법 알려드릴게용
- 파일이 함께 첨부되는 multipart/formdata 형식의 요청은 노션에 실제 api 명세서 작업 후 문서에 첨부해주셔야 합니다.

Spring Rest Docs 적용 및 예시 코드 첨부

---

frontend/__tests__/Select.test.tsx
frontend/public/icons/chevron-down.svg
frontend/src/app/_components/mypage/MyPageSelectBtns.tsx
frontend/src/app/_components/mypage/spot/MyPageSpotList.tsx
frontend/src/app/_components/ui/select/Select.tsx
frontend/src/app/_components/ui/select/SelectOption.tsx

#282 이슈를 바탕으로 select 컴포넌트를 작성했습니다.
공통 컴포넌트인 `viewPortal`를 이용해서 구현하려고 했으나 `option` 을 렌더링 하는 `<SelectOption />` 컴포넌트가 부모 컴포넌트인 `<Select/>` 태그에 종속되지 않고 백드롭에 종속되는 문제가 있었습니다.
이 전에 작성했던 FAB 버튼은 fixed로 정확히 위치가 정해져 있었어서 하위 컴포넌트도 문제 없이 사용할 수 있었는데 select 같은 경우는 어디에 위치할 지 모르기 때문에 `viewPortal`을 사용하지 않고 작성했습니다.
<br>
<br>
`ViewPortal` 컴포넌트를 사용하지 않고 select 컴포넌트를 작성했습니다.
나중에 리팩토링 할 때 `ViewPortal`을 사용할 수 있게 구조 변경을 고민해 볼 필요가 있을 것 같습니다.

마이 페이지에 존재하는 select를 기반으로 select 컴포넌트 작성

---

frontend/src/app/_components/api/httpRequest.ts

#298 을 처리하는 과정에서 생긴 오류를 수정합니다.
- `requestWithCookie`, `requestWithoutCookie`에 잘못 들어간 search param 구분자 `?`을 제거합니다.
어제 코드 작성하면서 약간 혼동이 와서 잘못 기입했는데, 오늘 mock api를 돌려보며 발견했습니다. 빠르게 처리 부탁드립니다~

잘못 들어간 search param 구분자 제거

---

frontend/src/app/_components/add/AddSpot.tsx

이전 코드에서는 장소 추가 플로우에서 검색 없이 다음으로 넘어가려 하는 경우만 막았었는데, 사용자가 검색 후 검색 결과에서 장소명을 클릭해 지도에 장소 마커가 표시된 이후 선택 없이 다음으로 넘어갈 수 있는 오류가 있어, 이를 수정합니다.
장소 추가를 위해 최상위에서 관리되는 `AddSpotProps`의 name이 빈 문자열인 경우 다음으로 넘어가지 않도록 합니다.

장소 추가 시 지도에서 장소를 선택하지 않아도 다음으로 넘어갈 수 있던 현상 수정

---

backend/support/domain/src/main/java/kr/co/yigil/member/Member.java

프로필 이미지 url을 잘못 전달하는 문제가 있어서 수정하였습니다.
<br>
<br>

hotfix : membr profile 이미지가 잘못 전달되는 문제 

---

frontend/src/app/(with-header)/(home)/action.ts
frontend/src/app/(with-header)/place/action.ts
frontend/src/app/_components/add/common/action.ts
frontend/src/app/_components/api/action.ts
frontend/src/app/_components/mypage/hooks/authenticateUser.ts
frontend/src/app/endpoints/api/auth/callback/google/route.ts
frontend/src/app/endpoints/api/auth/callback/kakao/constants.ts
frontend/src/app/endpoints/api/auth/callback/kakao/route.ts
frontend/src/app/utilActions.ts
frontend/src/middleware.ts
frontend/src/types/type.d.ts

- Node 환경에서 개발 환경을 나타내기 위해 일반적으로 `NODE_ENV` 환경 변수가 사용됩니다. 추가적인 환경 변수 사용을 피하기 위해, 기존에 `ENVIRONMENT` 환경 변수를 사용하던 코드를 `NODE_ENV`를 사용하도록 변경하였습니다.
- API 엔드포인트를 만들기 위해 BASE_URL을 얻어오는 과정이 매번 중복되어 해당 과정을 서버 액션 `getBaseUrl()`로 분리한 바 있습니다. 해당 코드를 사용하도록 통일합니다.
`httpRequest.ts`와 `myPageAction.ts` 관련 파일들은 서로 얽혀있는 것들이 많아, @davidktlee 님께서 정리해주실 필요가 있습니다. 따라서 `ENVIRONMENT` 환경 변수 타입 삭제는 잠시 유보하며, @davidktlee 님께서 관련 작업을 완료하신 후 함께 삭제해주시면 감사하겠습니다.

`ENVIRONMENT` 환경변수 제거 및 `getBaseUrl` 사용 통일

---

frontend/src/app/endpoints/api/auth/callback/google/route.ts
frontend/src/app/endpoints/api/auth/callback/kakao/constants.ts
frontend/src/app/endpoints/api/auth/callback/kakao/route.ts
frontend/src/app/utilActions.ts
frontend/src/middleware.ts
frontend/src/types/type.d.ts

#419 에서 `ENVIRONMENT` 환경 변수를 의존을 제거한 바 있습니다. 이 이유는 `NODE_ENV` 환경변수를 통해 API 백엔드 및 프론트엔드 도메인을 효과적으로 관리할 수 있다고 생각했기 때문입니다. 그러나 `NODE_ENV` 환경변수는 `production`, `development` 두 가지의 값만을 일반적으로 가질 수 있는 것으로 보입니다. `test`라는 값을 가질 수 있어 괜찮지 않나 생각했지만, `test`는 테스트 러너에서 실행될 때만 들어가는 값이었습니다... 따라서 환경 변수의 사용을 원래대로 복구합니다.
- `NODE_ENV`를 사용하도록 변경한 부분을 다시 `ENVIRONMENT` 환경 변수를 사용하도록 원상 복구합니다.

동작에 필요한 별도 환경 변수 복구

---

frontend/src/app/(with-header)/(home)/HomeNavigation.tsx
frontend/src/app/(with-header)/privacy-policy/page.tsx
frontend/src/app/_components/ui/popover/constants.tsx
frontend/src/app/_components/ui/popover/types.ts

구글 로그인을 위해 개인정보 처리방침 페이지를 추가했습니다. 
기존의 메인 페이지의 i 아이콘을 클릭하면 이동하며 페이지 내부에 구글 폼 링크도 같이 배치했습니다.
url은 루트에서 `/privacy-policy` 로 설정해두었습니다.
<br>
<br>

개인정보 처리방침 추가

---

backend/yigil-api/src/main/generated/kr/co/yigil/bookmark/interfaces/dto/mapper/BookmarkMapperImpl.java
backend/yigil-api/src/main/generated/kr/co/yigil/comment/interfaces/dto/mapper/CommentMapperImpl.java
backend/yigil-api/src/main/generated/kr/co/yigil/favor/interfaces/dto/mapper/FavorMapperImpl.java
backend/yigil-api/src/main/generated/kr/co/yigil/follow/interfaces/dto/FollowDtoMapperImpl.java
backend/yigil-api/src/main/generated/kr/co/yigil/login/interfaces/dto/mapper/LoginMapperImpl.java
backend/yigil-api/src/main/generated/kr/co/yigil/member/interfaces/dto/mapper/MemberDtoMapperImpl.java
backend/yigil-api/src/main/generated/kr/co/yigil/notification/interfaces/dto/mapper/NotificationMapperImpl.java
backend/yigil-api/src/main/generated/kr/co/yigil/place/interfaces/dto/mapper/PlaceMapperImpl.java
backend/yigil-api/src/main/generated/kr/co/yigil/region/interfaces/dto/mapper/RegionMapperImpl.java
backend/yigil-api/src/main/generated/kr/co/yigil/travel/interfaces/dto/mapper/CourseMapperImpl.java
backend/yigil-api/src/main/generated/kr/co/yigil/travel/interfaces/dto/mapper/SpotMapperImpl.java
backend/yigil-api/src/main/generated/kr/co/yigil/travel/interfaces/dto/mapper/TravelMapperImpl.java
backend/yigil-api/src/main/java/kr/co/yigil/comment/interfaces/controller/CommentApiController.java
backend/yigil-api/src/main/java/kr/co/yigil/member/interfaces/controller/MemberApiController.java
backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotInfo.java
backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/controller/TravelApiController.java
backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/response/MySpotsResponseDto.java
backend/yigil-api/src/main/resources/static/docs/comment-api.html
backend/yigil-api/src/main/resources/static/docs/course-api.html
backend/yigil-api/src/main/resources/static/docs/index.html
backend/yigil-api/src/main/resources/static/docs/notification-api.html
backend/yigil-api/src/main/resources/static/docs/place-api.html
backend/yigil-api/src/main/resources/static/docs/spot-api.html
backend/yigil-api/src/main/resources/static/docs/travel-api.html
backend/yigil-api/src/test/java/kr/co/yigil/comment/interfaces/controller/CommentApiControllerTest.java
backend/yigil-api/src/test/java/kr/co/yigil/member/interfaces/controller/MemberApiControllerTest.java
backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/SpotApiControllerTest.java
backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/TravelApiControllerTest.java

restful api를 지키고자 하는 노력의 일환으로 수정 하는 메서드를 post에서 put으로 변경
<br>
- 업데이트 메서드 변경
<br>
- multipart 리퀘스트는 기본적으로 post로 기본 설정되어 있는 것 같습니다. 때문에 put으로 변경하지 못했습니다.
- 동작 테스트 확인했습니다
- 단위 테스트 수정하고 확인했습니다.
- 문서화 업데이트 했습니다

491 update 메서드 post put 으로 변경

---

frontend/src/app/(with-header)/(home)/action.ts
frontend/src/app/(with-header)/(home)/page.tsx

홈페이지 장소 목록을 표시하기 위해 더보기만큼의 장소 개수를 불러오는 현상을 수정합니다.
- optional(`?`) 매개변수를 사용하도록 코드 변경

홈페이지 장소 목록에서 더보기만큼의 장소 개수가 로딩되는 현상 수정

---

backend/support/domain/src/main/java/kr/co/yigil/file/AttachFile.java
backend/support/domain/src/main/java/kr/co/yigil/global/SortBy.java
backend/support/domain/src/main/java/kr/co/yigil/member/Member.java
backend/support/domain/src/main/java/kr/co/yigil/travel/domain/Travel.java
backend/support/domain/src/main/java/kr/co/yigil/travel/domain/dto/CourseListDto.java
backend/support/domain/src/main/java/kr/co/yigil/travel/domain/dto/ImageFileDto.java
backend/support/domain/src/main/java/kr/co/yigil/travel/domain/dto/SpotListDto.java
backend/support/domain/src/main/java/kr/co/yigil/travel/infrastructure/SpotQueryDslRepository.java
backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberInfo.java
backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberServiceImpl.java
backend/yigil-api/src/main/java/kr/co/yigil/member/interfaces/dto/MemberDto.java
backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotInfo.java
backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/response/MySpotsResponseDto.java
backend/yigil-api/src/test/java/kr/co/yigil/member/interfaces/controller/MemberApiControllerTest.java
backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/SpotApiControllerTest.java

<br>
- querydsl을 적용하면서 내 정보 조회 spot image에 cdn이 붙지 않고 전달되는 문제 해결
- 내 정보에서 프로필 이미지를 없애는 기능을 추가하였습니다. (빈 문자열로 저장하고 빈 문자열을 전달합니다.
- 내 정보 조회에서 연령대의 필드 이름이 age로 되어 있던 부분을 ages 로 수정하였습니다.
<br>

512 bug spot image

---

backend/support/domain/src/main/java/kr/co/yigil/member/Member.java
backend/support/domain/src/main/java/kr/co/yigil/region/domain/Region.java
backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberCommand.java
backend/yigil-api/src/main/java/kr/co/yigil/member/domain/MemberInfo.java
backend/yigil-api/src/main/java/kr/co/yigil/member/interfaces/dto/MemberDto.java
backend/yigil-api/src/main/java/kr/co/yigil/region/domain/RegionInfo.java
backend/yigil-api/src/test/java/kr/co/yigil/member/domain/MemberServiceImplTest.java
backend/yigil-api/src/test/java/kr/co/yigil/member/interfaces/controller/MemberApiControllerTest.java

멤버의 회원 정보 중 favorite place의 지역 이름 정보 변경
<br>
- region 의 이름을 보여주는 부분을 region 엔티티 안에 getName()을 통해서 단일화 했습니다.
- profile 이미지를 없앨 경우 isProfileEmpty 필드를 true로 설정하도록 변경
- 이미지가 널이 아니고 isProfileEmpty 필드가 true일 경우 예외 발생 
- 프로필 이미지 관련 테스트 케이스를 추가하였습니다.
<br>
- 이상한 부분이 있으면 언제든지 말해주세요
-

524 member mypage

---

frontend/src/app/_components/add/Navigation.tsx
frontend/src/app/_components/add/common/PostRating.tsx
frontend/src/app/_components/add/common/PostReview.tsx
frontend/src/app/_components/add/course/AddCourseConfirm.tsx
frontend/src/app/_components/add/course/AddCourseData.tsx
frontend/src/app/_components/add/course/AddCourseImages.tsx
frontend/src/app/_components/add/course/AddCoursePlace.tsx
frontend/src/app/_components/add/course/AddCourseReviews.tsx
frontend/src/app/_components/add/course/AddCourseSpotData.tsx
frontend/src/app/_components/add/course/AddCourseSpots.tsx
frontend/src/app/_components/add/course/SelectSpot.tsx
frontend/src/app/_components/add/spot/AddSpotConfirm.tsx
frontend/src/app/_components/add/spot/AddSpotData.tsx
frontend/src/app/_components/add/spot/AddSpotImages.tsx
frontend/src/app/_components/add/spot/AddSpotPlace.tsx
frontend/src/app/_components/add/spot/AddSpotReview.tsx
frontend/src/app/_components/images/CourseImageHandler.tsx
frontend/src/app/_components/images/ImageHandler.tsx
frontend/src/app/_components/images/ImageInput.tsx
frontend/src/app/_components/images/ImagesContainer.tsx
frontend/src/app/_components/images/SpotImageHandler.tsx
frontend/src/context/travel/course/reducer.ts
frontend/src/context/travel/schema.ts

#499 에 이어, #483 에 대한 리팩토링 및 기능을 추가하였습니다.
- Spot을 추가하는 플로우 중 사진/리뷰 입력 및 기록 확정 화면을 재구현하였습니다.
- Course를 추가하는 플로우 중 사진/리뷰 입력 및 기록 확정 화면을 구현하였습니다.
- 기존에 동작하던 추가 로직이 동작하지 않습니다. `/test/{spot|course}` 링크에서 기능을 사용해볼 수 있습니다. `place` 추가 로직을 작성하지 않은 상태이기 때문에 임시로 place를 넣어주는 버튼을 넣어두었습니다. 임시이기 떄문에 넣을 수 있는 place 개수에 별도 제한은 두지 않았습니다.
- 해당 브랜치에 여러 PR을 제출할 예정이며 모든 작업이 끝나면 develop으로 병합할 예정입니다.

Spot/Course 추가 관련 리팩토링 및 기능 추가 - 2

---

backend/support/domain/src/main/java/kr/co/yigil/favor/domain/Favor.java
backend/support/domain/src/main/java/kr/co/yigil/place/infrastructure/PlaceRepository.java
backend/yigil-admin/src/main/java/kr/co/yigil/place/application/PlaceFacade.java
backend/yigil-admin/src/main/java/kr/co/yigil/place/domain/PlaceCommand.java
backend/yigil-admin/src/main/java/kr/co/yigil/place/domain/PlaceInfo.java
backend/yigil-admin/src/main/java/kr/co/yigil/place/domain/PlaceReader.java
backend/yigil-admin/src/main/java/kr/co/yigil/place/domain/PlaceService.java
backend/yigil-admin/src/main/java/kr/co/yigil/place/domain/PlaceServiceImpl.java
backend/yigil-admin/src/main/java/kr/co/yigil/place/infrastructure/PlaceReaderImpl.java
backend/yigil-admin/src/main/java/kr/co/yigil/place/interfaces/controller/PlaceApiController.java
backend/yigil-admin/src/main/java/kr/co/yigil/place/interfaces/dto/mapper/PlaceMapper.java
backend/yigil-admin/src/main/java/kr/co/yigil/place/interfaces/dto/response/PlaceMapResponse.java
backend/yigil-admin/src/test/java/kr/co/yigil/place/application/PlaceFacadeTest.java
backend/yigil-admin/src/test/java/kr/co/yigil/place/domain/PlaceServiceImplTest.java
backend/yigil-admin/src/test/java/kr/co/yigil/place/infrastructure/PlaceReaderImplTest.java
backend/yigil-admin/src/test/java/kr/co/yigil/place/interfaces/controller/PlaceApiControllerTest.java

- 관리자 페이지의 지도 뷰 구현을 위해 api를 추가합니다.
<br>
- 기존의 지도뷰에 사용하던 쿼리를 재사용하여, 어드민 지도뷰에 맞게 페이지를 출력합니다 (차이는 페이징 여부 말곤 없습니다)
<br>

613 관리자 페이지 장소 관리를 위한 api 작성

---

frontend/src/app/_components/add/course/AddCourseConfirm.tsx

일정 확인 화면에서 아래로 스크롤되어있을 때 상세 경로를 확인하기 위해 지도를 열면 X 버튼을 확인할 수 없는 오류를 수정합니다.
- DOM 구조를 수정하여 `800px`(Galaxy S20)까지는 모든 화면이 보이는 것을 (반응형 디자인 모드로) 확인했습니다.
- 지도를 여는 버튼에 `scrollTo` 함수를 적용하여 위로 스크롤하도록 수정하였습니다.

DOM 구조 수정 및 맵 여는 버튼 클릭 시 상단으로 스크롤되도록 구현

---

frontend/src/app/_components/add/AddTravelPlaceInfo.tsx
frontend/src/app/_components/add/course/action.ts
frontend/src/app/_components/naver-map/markers/basicMarker.ts
frontend/src/app/_components/naver-map/markers/plusMarker.ts

장소 대표 이미지에 지도 이미지가 입력되던 오류가 있었습니다.
추가로, 지도에서 장소 선택 시 매우 긴 장소 이름에 말줄임표가 적용되지 않던 오류가 있었습니다.
중간에 공백이 없는 매우 긴 문자열을 처리하기 위해서는 컨테이너의 최대 길이가 명시되어야 하며, `word-break: keep-all`이 적용되면 안됩니다. 명시된 컨테이너의 최대 길이보다는 작지만 공백이 있어 wrap되는 문자열을 처리하기 위한 방법인 `word-break: keep-all`과 상충되기 때문에 해당 속성을 제거합니다.
- 장소 대표 이미지에 지도 이미지가 입력되는 오류가 수정됩니다.
- 지도에서 장소 선택 시 매우 긴 장소 이름에 말줄임표가 적용되지 않던 오류가 수정됩니다.
- 장소 확인 화면의 주소에 대해 `word-break: keep-all`이 적용되었습니다.

장소 대표 이미지에 지도 이미지가 입력되는 현상 수정

---

backend/support/domain/src/main/java/kr/co/yigil/travel/domain/Spot.java
backend/yigil-admin/src/test/java/kr/co/yigil/travel/spot/domain/SpotServiceImplTest.java
backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotCommand.java
backend/yigil-api/src/main/java/kr/co/yigil/travel/domain/spot/SpotServiceImpl.java
backend/yigil-api/src/main/java/kr/co/yigil/travel/infrastructure/course/CourseSpotSeriesFactoryImpl.java
backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/mapper/SpotMapper.java
backend/yigil-api/src/main/java/kr/co/yigil/travel/interfaces/dto/request/SpotRegisterRequest.java
backend/yigil-api/src/main/resources/static/docs/course-api.html
backend/yigil-api/src/main/resources/static/docs/index.html
backend/yigil-api/src/main/resources/static/docs/report-api.html
backend/yigil-api/src/main/resources/static/docs/spot-api.html
backend/yigil-api/src/test/java/kr/co/yigil/travel/domain/spot/SpotServiceImplTest.java
backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/CourseApiControllerTest.java
backend/yigil-api/src/test/java/kr/co/yigil/travel/interfaces/controller/SpotApiControllerTest.java

스팟 생성 요청시 필요 없는 부분은 받지 않음으로서(특히 스팟과 플레이스의 중복된 이미지) 쓸데없이 네트워크 대역폭을 잡아먹지 않도록 변경
<br>
- 현재 디자인상에 없느 스팟의 제목을 받지 않도록 변경
- 장소와 스팟의 point가 별도로 설정할수 없어서 place point json을 별도로 받지 않도록 변경
- 장소의 이미지가 스팟의 첫 번째 이미지가 되도록 변경 
<br>
- 동작 확인 단위 테스트 했어유
- 조금 빨리 리뷰해주시면 감사하겠습니다!

616 spot 생성 요청 객체를 변경합니다

---

backend/yigil-api/src/main/java/kr/co/yigil/travel/infrastructure/spot/SpotSeriesFactoryImpl.java

spot 수정시 기존의 이미지를 비우고 새 이미지를 추가할 때 널을 참조하여 발생하는 오류 발생
<br>
- 널일때 새 리스트를 만들어서 오류가 나지 않도록 했습니다.
<br>

spot 수정시 기존의 이미지를 비우고 새 이미지를 추가할 때 발생하는 오류 해결

---

frontend/src/app/_components/place/spot/Spot.tsx
frontend/src/types/response.ts

백엔드 API 응답 데이터 타입이 변경되어 관련된 부분을 수정합니다.
- `Spot` 스키마의 `image_url_list` 컬럼명을 `image_urls`로 변경하였습니다.
- `Spot`, `Course` 스키마에 `following` 컬럼을 추가하였습니다.

백엔드 응답 데이터 타입 수정에 따라 맞추기

---

frontend/src/app/(with-header)/(home)/LoggedOutHome.tsx
frontend/src/app/_components/place/FollowButton.tsx
frontend/src/app/_components/place/course/Course.tsx
frontend/src/app/_components/place/places/action.ts
frontend/src/app/_components/place/spot/Spot.tsx
frontend/src/utils.ts

장소 상세 화면의 각 Spot/Course 작성자를 팔로우/언팔로우할 수 있도록 UI와 기능을 추가했습니다.
- 현재 팔로우 상태에 따라 문구가 바뀌는 버튼을 추가했습니다. 해당 버튼은 비로그인 시, 작성자가 본인일 경우에는 표시되지 않습니다.
- 현재 팔로우 상태에 따라 팔로우/언팔로우하는 서버 액션을 추가했습니다. 해당 기능은 #655 에서 이미 개발되었지만, PR 승인이 늦춰졌으므로 별도로 작성해넣었습니다.
- 백엔드 API 응답을 파싱하는 로직을 별도의 함수로 분리하여 `util.ts`에 위치시켰습니다. 해당 함수는 응답에 성공했을 때 파싱에 사용할 스키마(타입 TSomething)와 파싱할 json 객체를 입력으로 받아 `TBackendRequestResult<TSomething>`을 반환하는 함수입니다.

장소 상세 화면에서 각 Travel 작성자를 팔로우/언팔로우할 수 있는 기능 추가

---

frontend/src/app/_components/mypage/course/CourseDetail.tsx
frontend/src/types/myPageResponse.ts

API 응답과 프론트엔드에서 받는 스키마 간의 컬럼명이 맞지 않아 오류가 발생하는 현상을 수정합니다.
- `myPageCourseDetailSchema`의 `create_date`를 `created_date`로 수정합니다.

API 응답 컬럼명 수정

---

frontend/src/app/_components/add/course/without-new/ExistPlaceItem.tsx
frontend/src/app/_components/mypage/spot/MyPageSpotItem.tsx
frontend/src/app/_components/notification/NotificationIcon.tsx
frontend/src/types/myPageResponse.ts

Fix mypage schema

---

frontend/src/app/(without-header)/login/page.tsx
frontend/src/app/_components/ui/button/CloseButton.tsx
frontend/src/app/endpoints/api/auth/callback/google/route.ts
frontend/src/app/endpoints/api/auth/callback/kakao/route.ts
frontend/src/app/endpoints/api/auth/callback/naver/route.ts
frontend/tailwind.config.ts

로그인 실패의 경우가 4가지 있는데 각 경우에 대해 `NextReponse.redirect`를 이용해 login화면으로 리다이렉트 시키며, `searchParams`로 상태를 보여줬습니다.
`status`를 `failed`로 처리해 실패했다는 것을 나타내고 화면에 에러 문구를 출력했습니다.
`reason` 이라는 `searchParam`으로 현재 에러에 대해 얻어오는 정보에서의 에러인지 백엔드와의 통신 에러인지 `code`, `userinfo`, `server` 세 가지 경우로 처리했습니다.
<br>
<br>

feat: 로그인 실패 시 로그인화면 에러 출력
